### ISSUE TITLE
[Bug]: min and max doesn't work for Input

### ISSUE THREAD

**Issue by verbeckii** [cloudscape-design/components#1002]
### Browser

Chrome

### Package version

3.0.251

### React version

18.2.0

### Description

I was going to create a simple input field for Start/End hour
So it is so easy logic to allow users to choose number within range 0-23
So I expected added min={0}, max={23} to [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) should works

### Source code

```
            <FormField label="Start Hour">
              <Input
                value={value}
                onChange={(event) => setValue(event.detail.value)}
                type="number"
                min={0}
                max={23}
              />
            </FormField>
```

### Reproduction

https://codesandbox.io/s/priceless-ramanujan-7ybvcu?file=/src/App.js

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by alfonsoar** [comment]
@just-boris having to do manual validation with `errorText` seems like some additional overhead (considering the native `<input />` element supports it). 

For example in this case, I think we can provide a better user experience to users by preventing them from ever going below a certain number rather then displaying an error. 

I know the CloudScape APIs currently do not contain `min` or `max` but can we consider adding them in a future major version?

**Comment by just-boris** [comment]
This is our design decision to make validation look this way. Currently there are no plans changing this decision, so we cannot leverage built-in attributes because they look and behave differently than our design wants
