### ISSUE TITLE
[Bug]: Filtering and sorting doesn't work for nested fields

### ISSUE THREAD

**Issue by verbeckii** [cloudscape-design/components#1046]
### Browser

Chrome

### Package version

3.0.235

### React version

18.0.2

### Description

I have a table with **PropertyFilter** and my table data looks like:
```
const data = [
  {
    name: "Item 1",
    alt: "First",
    Customers: { Description: "Main Customer" }
  },
  {
    name: "Item 2",
    alt: "Second",
    Customers: { Description: "Second Customer" }
  },
  {
    name: "Item 3",
    alt: "Third",
    Customers: { Description: "Test Customer" }
  }
];
```

The problem is the Customer field as you can see its objects with the Description key.
So I can easily define table columns like this: **Customers.Description** but this syntax doesn't work for filtering and also my table can't do sorting by Customer column too 

It seems like something happened while it preparing FilteringOptions

![image](https://user-images.githubusercontent.com/60220767/235849771-fe5709af-6092-4318-986f-67b5c74f21a8.png)
 

### Reproduction

https://codesandbox.io/s/bold-shamir-fx5t73?file=/src/App.js

You can reproduce it in my codesandbox:
1. try to do sorting by Customer field: it doesn't sort
2. try to use the filter for CUstomer: id doesn't find any values

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by jperals** [comment]
Hello,

We are working on supporting nested keys in Property Filter (see https://github.com/cloudscape-design/collection-hooks/issues/30) but at the moment this will not work the way you wrote it. If this is acceptable for you, I would suggest flattening your data items, something like this:

```
const data = [
  {
    name: "Item 1",
    alt: "First",
    Customers: "Main Customer"
  },
  {
    name: "Item 2",
    alt: "Second",
    Customers: "Second Customer"
  },
  {
    name: "Item 3",
    alt: "Third",
    Customers: "Test Customer"
  }
];
```

**Comment by verbeckii** [comment]
> Hello,
> 
> We are working on supporting nested keys in Property Filter (see [cloudscape-design/collection-hooks#30](https://github.com/cloudscape-design/collection-hooks/issues/30)) but at the moment this will not work the way you wrote it. If this is acceptable for you, I would suggest flattening your data items, something like this:
> 
> ```
> const data = [
>   {
>     name: "Item 1",
>     alt: "First",
>     Customers: "Main Customer"
>   },
>   {
>     name: "Item 2",
>     alt: "Second",
>     Customers: "Second Customer"
>   },
>   {
>     name: "Item 3",
>     alt: "Third",
>     Customers: "Test Customer"
>   }
> ];
> ```

Hello

Thanks for answer
I'll be waiting for supporting nested keys and now can move with your suggestion - flattening data

**Comment by jperals** [comment]
Glad to hear that you have a way forward. I will close this issue for the time being. Feel free to reach out to us again if you need any help.
