### ISSUE TITLE
[Feature Request]: Modifiable Rating Component

### ISSUE THREAD

**Issue by ebertjen** [cloudscape-design/components#1068]
### Description

I would like to request a (Star) rating component such as this one available in Amplify:
https://ui.docs.amplify.aws/react/components/rating

Note that the Amplify component is read-only, but I'd love to have a modifiable component that allows users to also select a rating by hovering the mouse and clicking, such as on amazon.com when you create a product review.

The component should be customizable in a similar way as the linked Amplify component with sensible defaults that go well together with the Cloudscape design system, especially coloring and spacing.

I'd suggest to allow wrapping this new input component within a `FormField` to support labels, documentation and validation errors.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by YueyingLu** [comment]
Hi @ebertjen,

thanks for reaching out. This feature request does seem like a reasonable addition to the Cloudscape Design System, however we don’t have any plans for this change in the short-term future. We will post updates on this thread, when any plans changes. We will keep this feature request open to get more feedbacks.

**Comment by just-boris** [comment]
Closing due to low interest in this feature. Currently this component is not in our plans
