### ISSUE TITLE
[Feature Request]: ability to configure name for radio input created by Tiles component

### ISSUE THREAD

**Issue by kamaz** [cloudscape-design/components#1127]
### Description

Currently, the Tiles component does not expose a 'name' property, which makes it quite challenging to use with native Forms and FormData.

Is there any particular reason for hiding this property and preventing it from being set?

In the code, I noticed that the line [`generateName`](https://github.com/cloudscape-design/components/blob/ffc07e6074ada93bbe964e3b7e57bb64d06b85b9/src/tiles/internal.tsx#L67) is passed to a Tile component.

My proposal is to add a 'name' property, similar to the 'Input' component, and utilize 'generatedName' when 'name' is not specified.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by Al-Dani** [comment]
Hi @kamaz 

Thank you for the suggestion, it would be a reasonable addition to Tiles API. We will add it to our backlog and keep you posted.

If you are interested in contributing this feature to our system, we would be happy to guide you! You can check our [contribution guidelines](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md).
When adding property description,  you can get an inspiration from the respective property in [RadioGroup](https://cloudscape.aws.dev/components/radio-group/?tabId=api).

Best,
Cloudscape

**Comment by Al-Dani** [comment]
Apologies, I fixed the link.
But of course, you can use src/radio-group/interfaces.ts!

Thank you!
