### ISSUE TITLE
[Feature Request]: Separate colours for destructive operations for components like Button

### ISSUE THREAD

**Issue by kamaz** [cloudscape-design/components#1131]
### Description

I was wondering if it's possible to configure a separate color for destructive operations. From what I understand, it seems impossible unless you duplicate the components you want to modify.

Is there an example of how to achieve this? Also, I think it would be beneficial to have this feature included in the core library. Having a distinct colour for destructive operations, like a `Delete` button, compared to non-destructive actions, such as a `Save` button, is a widely used design approach. It more effectively communicates the potential consequences of an action to users, enhancing their experience by providing clear visual cues and reducing the chances of accidental or unintended actions.

Example:

<img width="240" alt="Screenshot 2023-05-26 at 14 36 08" src="https://github.com/cloudscape-design/components/assets/2106178/70c2adf6-4b0c-4741-8d23-98f53b2d2384">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by kamaz** [comment]
@at-susie thank you for clarifying the current limitations. 

Do you have any suggestions on how it could be achieved distinctive background colors for buttons within the framework's scope? (happy with alternative options or workarounds)

**Comment by connorlanigan** [comment]
Applying a different background colour for a button is currently not supported in Cloudscape.

(Cloudscape has a theming functionality, but that changes the appearance of _all_ buttons in the application).
