### ISSUE TITLE
[Feature Request]: Allow TextContent in ButtonDropdownProps.Item

### ISSUE THREAD

**Issue by ianmarmour** [cloudscape-design/components#1200]
### Description

Currently the [ButtonDropDownProps.Item](https://github.com/cloudscape-design/components/blob/0180c66aac026af94a3d9d8664ef75c027535df3/src/button-dropdown/interfaces.ts#L105-L119) interface only allows for `string` types to be used in the text field. I would like to be able to provide formatted sections of text either via a custom component or the [TextContent ](https://github.com/cloudscape-design/components/blob/0180c66aac026af94a3d9d8664ef75c027535df3/src/text-content/index.tsx#L13-L23) component to allow for more advanced drop down menu creation similar to the AWS Console's region selection drop-down as pictured below,

> ![EC2_select_region](https://github.com/cloudscape-design/components/assets/12246835/cda6c0d5-00a0-4c9b-ab93-3d804f8a6638)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by johannes-weber** [comment]
Hi @ianmarmour,

thanks for reaching out! This feature request does seem like a reasonable addition to the Cloudscape Design System, however we don’t have any plans for this change in the short-term future. We will post updates on this thread, when any plans changes.

We will leave this issue open for visibility and for gathering further feedback
