### ISSUE TITLE
[Documentation]: NextJS Instructions Typo

### ISSUE THREAD

**Issue by danielgsims** [cloudscape-design/components#1229]
### Description

On the page: https://cloudscape.design/get-started/integration/using-cloudscape-components/

The next config has a typo in the package name here:

```
const nextConfig = {
  transpilePackages: [
    '@cloudscape-design/components',
    '@cloudscape-design/components-toolkit'
  ]
};
```

The second package should be "component" and not "components". That took an embarrassing amount of time to find that bug!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
Good catch, thanks for reporting.

I made the change already, and I resolve the issue after I see it deployed
