### ISSUE TITLE
[Feature Request]: Support for cases where `pagesCount` cannot be set in `Pagination` component

### ISSUE THREAD

**Issue by rktyt** [cloudscape-design/components#123]
### Description

Difficult to use `Pagination` when listing users in `AWS Cognito`.

Reason:
Some services are not easy to obtain total data counts.
(See detail: <https://stackoverflow.com/questions/69316247/aws-cognito-user-pool-total-users-count-and-querying>

This is not limited to AWS services, only prev, next information may be provided.
So it would be good to have only PREV, NEXT links.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by timogasda** [comment]
Hello,
if you cannot determine your number of pages (`pagesCount`) from the beginning, you can use open-ended pagination with the `openEnd` property of Pagination, see the [open-ended pagination example](https://cloudscape.design/components/pagination/?tabId=playground&example=open-end). You can also find some usage guidelines in the pagination article: https://cloudscape.design/components/pagination/?tabId=usage.

In practice, you can combine the utilities from our [collection hooks](https://cloudscape.design/get-started/dev-guides/collection-hooks/) with the `openEnd` property.

Let's imagine you have a custom hook that handles your data fetching from the server and tells you when you have reached the end of your collection (called `useData`). This could look something like this:

```jsx
function OpenEndedPagination() {
  const [pageIndex, setPageIndex] = useState(1);

  const { items: allItems, hasMoreData } = useData(pageIndex);

  const { collectionProps, paginationProps, items } = useCollection(allItems, {
    pagination: { pageSize: PAGE_SIZE }
  });

  return <Pagination
    {...paginationProps}
    openEnd={hasMoreData}
    onNextPageClick={({ detail: { requestedPageIndex } }) => {
      setPageIndex(requestedPageIndex);
    }}
  />
}
```

Full example: https://codesandbox.io/s/fervent-water-plebul?file=/src/App.js

Hope that helps! :)

**Comment by rktyt** [comment]
Thanks!
I assumed that the `pagesCount` property was not available in this case because it was a required field.
