### ISSUE TITLE
[Bug]: cannot use onFollow for TopNavigation identity

### ISSUE THREAD

**Issue by lescaudr** [cloudscape-design/components#125]
### Package version

3.0.13

### React version

18.1.0

### Description

I'd like to use the onFollow event for the top navigation link to avoid refreshing the full page but it's doesn't allow me to.
I think something must be wrong from typescript?

![image](https://user-images.githubusercontent.com/9129639/183047961-1db62501-d82d-4022-8ae8-2354e345c95e.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by timogasda** [comment]
Hello!

It looks like you have a small typo in your code. When setting the `onFollow` property in `TopNavigation` you need to use `:` instead of `=` because you are passing an object:

```jsx
<TopNavigation
  identity={{
    href: "/",
    title: "My Website",
    onFollow: (event) => { /* ... */ }
  }}
/>
```

**Comment by lescaudr** [comment]
Omg I need to sleep and feel really stupid. Sorry.
You can delete this...

**Comment by timogasda** [comment]
No worries at all!
