### ISSUE TITLE
[Feature Request]: Select All option for MultiSelect and Select Component 

### ISSUE THREAD

**Issue by naveen8801** [cloudscape-design/components#1278]
### Description

It is common to expect the **Select All** option by a MultiSelect and Select component implicitly so that the user can easily Select or Deselect all options if he wants to. It will surely enhance the user experience 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by abdhalees** [comment]
Hello @naveen8801, 

For `Select` we cannot support this feature as the component only selects one option, for MultiSelect it's possible to achieve this by grouping options in one group, [see this example](https://codesandbox.io/s/nostalgic-silence-y5jcdp?file=/src/App.js)

we understand that this is a workaround and we agree that this feature would be a reasonable addition to the Cloudscape Design System. However, we don’t have a plan for this change in the short-term future.

**Comment by naveen8801** [comment]
Hey @abdhalees, thnx for the example 👍
