### ISSUE TITLE
Adding A flexBox or some similar component

### ISSUE THREAD

**Issue by fidel-tensoriot** [cloudscape-design/components#1298]
### Description

I end up having to jump out of cloudscape and into custom css for flex properties. for example If I wanted to center an item on the page or space-between or around. The space evenly can be accomplished using the `import SpaceBetween from "@cloudscape-design/components/space-between";` component but as stated it would be helpful to be able to have some flex features. One limitation to space between is that it has a max of something like `xxl` as a value.

{
  display: flex
  direction: column/row
  justify-content: center/space-between/space-around/space-evenly;
}

Material UI offers styling thru the system properties. 
https://mui.com/system/properties/

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by abdhalees** [comment]
Hello @fidel-tensoriot, 

SpaceBetween has an [alignItems](https://cloudscape.design/components/space-between/?tabId=api) property, but if you need more custom properties we'd recommend to use css directly. 
our components like SpaceBetween, ColumnLayout and Grid covers some of the generic use cases, if you have specific use cases then using css is your best option.

**Comment by just-boris** [comment]
Closing this. We develop a "design system" which means that all our components encapsulate some sort of design decisions. We provide utility components to help implement our designs, but we have no intent to cover the entirety of CSS
