### ISSUE TITLE
Expose font size and weight as Themeable properties

### ISSUE THREAD

**Issue by sjakos** [cloudscape-design/components#1330]
### Description

Font family is exposed as themeable, but font size is not. The font I'd like to use to be consistent with brand guidelines on a project I'm working on doesn't display well with the default of 14px, making the page less accessible. I'd like to be able to configure the fontSize properties when generating a themed build of Cloudscape to maintain accessibility guidelines with a brand consistent font.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by rubencarvalho** [comment]
Hello Sam!

Allowing this does seem like a sensible addition to the system, however we don’t have any plans for making this change at the moment. We will keep this issue open to collect any additional feedback or use cases.

Thank you.

**Comment by bilalq** [comment]
This is a pretty crucial feature for being able to adopt this design system to match most designs.

**Comment by just-boris** [comment]
"Design system" means that there is already a predefined design. Theming was never intended to convert our design system to another design. It is only to make small visual adjustments

**Comment by bilalq** [comment]
That's fair. But I'd consider adjusting font sizes and weights to fall under the classification of "small visual adjustments".

**Comment by just-boris** [comment]
The ticket stays open, because the OP request is something we want to address. However "match most designs" is not a goal for our project.

**Comment by bilalq** [comment]
Apologies for my wording. By "most designs", I really only meant derivative designs of the underlying system. Things like tuning color palette, fonts, and border radiuses. Most of these are already supported.

**Comment by connorlanigan** [comment]
We have released themeable tokens for font sizes and font weights. You can find the list of tokens in the "Typography" tab of [our token list on our website](https://cloudscape.design/foundation/visual-foundation/design-tokens/#tokens).
