### ISSUE TITLE
[Bug]: Expandable Section headingTagOverride does not work

### ISSUE THREAD

**Issue by msorial44** [cloudscape-design/components#1360]
### Package version

3.0.339

### React version

v18.2.0

### Description

The overrideHeadingTag seems to have no effect on how the Expandable Section component renders at all.

### Reproduction

https://codesandbox.io/s/small-mountain-x3k4v2?file=/src/App.js 
or
https://cloudscape.design/components/expandable-section/?tabId=playground&example=container

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
This property changes the HTML semantic element being used, but no visual changes.

Checked the codesanbox and it looks expected

<img width="477" alt="image" src="https://github.com/cloudscape-design/components/assets/812240/b097de82-3651-4f5a-bc4d-b02fdcdae779">

**Comment by msorial44** [comment]
What is the use case for such a property? And is there a way to render it as h5 rather than just changing the tag.

**Comment by just-boris** [comment]
This property allows have proper semantic elements nesting like this one

* h1 
   * h2
        * h3
            *  h4
                * h5

Visual appearance can be changed via `variant` property, we offer a few options there

**Comment by msorial44** [comment]
I am trying to change the header size of an Expandable Section. So my only options are the font size of div or h2?

**Comment by just-boris** [comment]
We provide variants according to supported use-cases. You need to pick the variant accordingly.

If you give more details about your use-case, I can give more guidance which variant to use

**Comment by msorial44** [comment]
I am using a container that contains certain information. There may be around ~50 of these on a page. The size of the header in the container variant is too large but I also want to use the headerInfo and headerActions props which are disabled in the other variants. How can I change the header size?

**Comment by just-boris** [comment]
If you want to render buttons next to the header, it will be 30px high at least. The header size does not matter at this point anymore, because buttons take the height anyway.

If you want to render action buttons, container variant is the only way

**Comment by msorial44** [comment]
I want to change the font size of the headerText. Is this possible while maintaining the variant as container?

**Comment by just-boris** [comment]
No, not possible
