### ISSUE TITLE
[Bug]: Popover does not work on a scaled canvas

### ISSUE THREAD

**Issue by brianfoody** [cloudscape-design/components#141]
### Browser

Chrome

### Package version

3.0.18

### React version

18.2.0

### Description

The Popover should display adjacent to the selected element but instead it is placed further left on a zoomed out div and further right on a zoomed in div.

### Source code

<div id="canvasContainer" style="width: 25000px; height: 15000px; background: white; border: 2px dashed black; position: absolute; transform: matrix(0.35639, 0, 0, 0.35639, -14909.5, -8102.23); transform-origin: 15375.5px 8286.23px;">
<div>
    <Popover
      dismissButton={false}
      position="top"
      size="small"
      triggerType="custom"
      content={
        <TextContent>
          Content here
        </TextContent>
      }
    >
      <div>
        <TbInfoCircle size={16} />
      </div>
    </Popover>
</div>
<div>

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by rubencarvalho** [comment]
Hello Brian,

thanks for reaching out.

I was only able to reproduce what you've mentioned in our [Popover component page](https://cloudscape.design/components/popover/?tabId=playground), by setting, for example, `transform: scale(0.5)` in the Playground content element.
Standard zoom from Chrome 103 didn't impact the component for me. Which browser are you using?

Nonetheless, using the `renderWithPortal` property solved this for me. Enabling this property will allow the popover to be rendered in the root stack context using [React Portals ](https://reactjs.org/docs/portals.html) (however, depending on your use case - ie: if `transform: scale` is applied to the whole document - this might not be the solution).

Could you please share your source code with us or let us know if enabling that property solved it for you?

Thank you,
RC

**Comment by brianfoody** [comment]
@rubencarvalho that does the trick, amazing buddy thanks! How did I not know about React portals also!? Thanks for the bit of education too ;-)
