### ISSUE TITLE
[Feature Request]: Avatar + User Card component

### ISSUE THREAD

**Issue by AdamJ** [cloudscape-design/components#1422]
### Description

As a user, it would be greatly beneficial to have an avatar + user card component available, where an icon or custom image could be added that included the user's name and, if desired, any additional information pulled from an API or included JSON or YAML file.

Current areas where this component could be utilized:
- Cards
- Table
- Tiles
- Top navigation (replacing the existing Customer Name drop-down with generic icon)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by AdamJ** [comment]
Thank you for the update @gethinwebster. If desired, I would be happy to submit a design for consideration, following the contribution guidelines.

**Comment by gethinwebster** [comment]
We recently released an [avatar component](https://cloudscape.design/components/avatar/). It is more focused on the first part of the request here, but could be combined with other components to create richer user information experiences.
