### ISSUE TITLE
[Feature Request]: Support themeing of Segmented Control component

### ISSUE THREAD

**Issue by bilalq** [cloudscape-design/components#1424]
### Description

Component link: https://cloudscape.design/components/segmented-control/?tabId=playground

Ideally, this component would either respect button theming or expose design tokens to allow users to theme it directly. Currently, neither of those seem possible.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by jperals** [comment]
Hi @bilalq,

Sorry for the late response. This sounds like a sensible addition so I have started to draft a PR for it.
