### ISSUE TITLE
[Bug]: Incorrect <SplitPanel> word wrapping

### ISSUE THREAD

**Issue by ianmarmour** [cloudscape-design/components#1431]
### Browser

Firefox

### Package version

v3.0.311

### React version

v18.2.0

### Description

The split panel's `word-wrapping` does not correctly account for large contiguous header strings. Specifically the word-wrap property is set to `break-word` however if a header contains a long contiguous string this behaves incorrectly. Because of this incorrect word wrapping the split panel when used in the side layout overflows and forces uses to horizontally scroll. The solution for this should be very simply simply add an additional CSS property [here](https://github.com/cloudscape-design/components/blob/main/src/split-panel/styles.scss#L34) for `word-break` set to `break-all` to ensure there's no overflow even if it's a long contiguous string.

### Reproduction

Simply create a split panel with a long string set as the header value, limit the maximum size of the split panel to something small and then set the split panels position to side.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by ianmarmour** [comment]
For what it's worth this same behavior also seems to be impacting table cells, it would be great if we could also break-all there for consistency.

**Comment by just-boris** [comment]
Fixed in [v3.0.359](https://github.com/cloudscape-design/components/releases/tag/3.0.359)
