### ISSUE TITLE
[Feature Request]: Any plans to create Vue port of Cloudscape?

### ISSUE THREAD

**Issue by eiva** [cloudscape-design/components#1456]
### Description

Thanks for open sourcing that nice and consistent UI library.
But there is a question: in documentation front page it is written that

> Cloudscape is an open source design system to create web applications.

While in reality it is react UI library. While it is amazing that it is open sources - it still pretty limiting.

Is there any plans to create port for Vue?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
No, there is no such plans
