### ISSUE TITLE
[Feature Request] Login/Registration pattern

### ISSUE THREAD

**Issue by weisisheng** [cloudscape-design/components#156]
### Description

Hey Gang-  Love the overall offering to the community; it's terrific.  Since my design skills are not great, inquiring here about a standard login which matches with the "internal" pages.  Thanks in advance.  

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by gethinwebster** [comment]
Thanks for the feedback and for opening this request. This is unfortunately something that we're unlikely to work on as we don't see big value for our key target customers.

However, you could apply some of the concepts from the more fundamental design patterns to design these pages:
- https://cloudscape.design/patterns/resource-management/create/single-page-create/
- https://cloudscape.design/patterns/general/validation/
- https://cloudscape.design/patterns/general/user-feedback/
