### ISSUE TITLE
[Feature Request]: Hide Autosuggest Search Icon

### ISSUE THREAD

**Issue by yossyX** [cloudscape-design/components#1589]
### Description

I'd like to use Autosuggest instead of the Input in the form. I believe the search icon is unnecessary. Is there a way to hide it?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
This is a deliberate design decision: https://github.com/cloudscape-design/components/issues/434

Currently we have no plans to change it
