### ISSUE TITLE
[Bug]: Missing Export useRuntimeVisualRefresh when using Container @cloudscape-design/components@3.0.394 

### ISSUE THREAD

**Issue by kziemski** [cloudscape-design/components#1595]
### Browser

Chrome

### Package version

v3.0.394

### React version

v18

### Description

export 'useRuntimeVisualRefresh' was not found in '@cloudscape-design/component-toolkit/internal' when using container from components.  board-components has the same problem with the latest version. 
i see its the export is likely already commited just wanted to log the error for the current published version 

### Reproduction

upgrade components to v3.0.394

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by pan-kot** [comment]
Hello,

The issue might be caused by an outdated version of the @cloudscape-design/component-toolkit package. Could you please install the latest versions of @cloudscape-design/components and @cloudscape-design/component-toolkit and see if the issue is still reproducible?

**Comment by kziemski** [comment]
looks like this got fixed in the latest
