### ISSUE TITLE
[Feature Request]: `Link` should support a `title` prop

### ISSUE THREAD

**Issue by quisido** [cloudscape-design/components#1599]
### Description

For SEO and accessibility purposes, I would like my `<Link>` components to support a `title` prop that becomes the resulting `<a>`'s `title` attribute.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by gethinwebster** [comment]
Just checking in that we're looking into this.

**Comment by just-boris** [comment]
Hello!

We have looked into that, but found no use-cases to support it. Closing this for now, but let us know if you have any use-cases or links to requirements saying you need to support this
