### ISSUE TITLE
[Bug]: Select component with filtering auto crashing when options have value of int type

### ISSUE THREAD

**Issue by naveen8801** [cloudscape-design/components#1605]
### Browser

Edge

### Package version

3.0.235

### React version

18.2.0

### Description

Select component with filtering auto crashing when trying to filter options and options has value of integer type for example - 

```
const options = [
  { label: "Day 1", value: 1 },
  { label: "Day 2", value: 2 },
  { label: "Day 3", value: 3 }
];
```

### Source code

Link - https://codesandbox.io/s/magical-elgamal-7mtwfj?file=/src/App.js:0-603

```
import { useState } from "react";
import "./styles.css";
import { Select } from "@cloudscape-design/components";

const options = [
  { label: "Day 1", value: 1 },
  { label: "Day 2", value: 2 },
  { label: "Day 3", value: 3 }
];

export default function App() {
  const [selectedOption, setSelectedOption] = useState(options[0]);
  return (
    <div className="App">
      <Select
        options={options}
        selectedOption={selectedOption}
        filteringType="auto"
        onChange={({ detail }) => {
          setSelectedOption(detail.selectedOption);
        }}
      />
    </div>
  );
}

```

### Reproduction

* Open https://codesandbox.io/s/magical-elgamal-7mtwfj?file=/src/App.js:0-603
* Type something in the filter input field

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by gethinwebster** [comment]
Integers aren't supported as select option values. This is reflected both in the TypeScript typings and the API documentation  (https://cloudscape.design/components/select/?tabId=api), and also reflects the behavior of the native HTML Select on which this component is based.
