### ISSUE TITLE
Donut Chart - Uncaught TypeError: Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by daniellehillman** [cloudscape-design/components#1648]
### Browser

Chrome

### Package version

3.0.276

### React version

18.2.0

### Description

While integrating a donut chart into a project, a few TypeErrors will pop up after hovering over/clicking on sections of the donut chart. I am using the data and code provided by cloudscape, so the data shouldn't be coming back as null. There has not been a single use case to reproduce this, it just occurs between seconds and a minute/two minutes of hovering over any part of the donut chart.
![Screenshot 2023-10-12 at 10 18 12 AM](https://github.com/cloudscape-design/components/assets/66494738/858172f8-8849-4585-843b-62cb2b67bbd5)
![Screenshot 2023-10-11 at 3 09 01 PM](https://github.com/cloudscape-design/components/assets/66494738/5d51dc96-b574-4b27-adc5-521b40f133a4)

### Source code

  <PieChart
        data={[
          { title: "Item A", percentage: 40, value: 40 },
          { title: "Item B", percentage: 25, value: 25 },
          { title: "Item C", percentage: 20, value: 20 },
          { title: "Item D", percentage: 10, value: 10 },
          { title: "Item E", percentage: 5, value: 5 },
        ]}
        visibleSegments={[
          { title: "Item A", percentage: 40, value: 40 },
          { title: "Item B", percentage: 25, value: 25 },
          { title: "Item C", percentage: 20, value: 20 },
          { title: "Item D", percentage: 10, value: 10 },
          { title: "Item E", percentage: 5, value: 5 },
        ]}
        segmentDescription={(datum, sum) =>
          `${datum.value} units, ${((datum.value / sum) * 100).toFixed(0)}%`
        }
        ariaDescription="Donut chart showing generic example data."
        ariaLabel="Donut chart"
        innerMetricDescription="total units"
        innerMetricValue="100"
        hideFilter
        additionalFilters={
          <FormField label="Filter displayed data">
            <Select
              options={[
                { label: "Data source", value: "1" },
                { label: "Energy type", value: "2" },
              ]}
              selectedOption={selectedOption}
              placeholder="Data source"
              onChange={({ detail }) => {
                setSelectedOption(detail.selectedOption as any);
              }}
            />
          </FormField>
        }
        size="large"
        variant="donut"
        empty={
          <Box textAlign="center" color="inherit">
            <b>No data available</b>
            <Box variant="p" color="inherit">
              There is no data available
            </Box>
          </Box>
        }
        noMatch={
          <Box textAlign="center" color="inherit">
            <b>No matching data</b>
            <Box variant="p" color="inherit">
              There is no matching data to display
            </Box>
            <Button>Clear filter</Button>
          </Box>
        }
      />

### Reproduction

<img width="477" alt="Screenshot 2023-10-12 at 10 22 17 AM" src="https://github.com/cloudscape-design/components/assets/66494738/7673192b-ccb9-4dd2-82fe-f34e5a6bd511">

Hovering over parts of the donut chart. Doesn't happen instantly or on a reload.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by rubencarvalho** [comment]
Hello Danielle,

Could you please update the package to the latest version? We've released a fix for the issue you reported in this pull request: https://github.com/cloudscape-design/components/pull/1374.

You can find the release here: https://github.com/cloudscape-design/components/releases/tag/3.0.349

Once you've updated, let us know if that resolves the issue you were facing.

Thank you,
Ruben

**Comment by jperals** [comment]
Closing this issue as this should be fixed by the aforementioned PR. Feel free to reopen if you keep encountering the issue.
