### ISSUE TITLE
Placeholder for Select

### ISSUE THREAD

**Issue by j-man-jerry** [cloudscape-design/components#1667]
### Description

The placeholder option for the Select component is not working. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by johannes-weber** [comment]
Hi @j-man-jerry, thanks for reaching out!
Could you get us more details how we can reproduce the problem e.g. by providing a reproducible example?

I was not able to reproduce a non working `placeholder` property on the `Select` component ([example on CodeSandbox](https://codesandbox.io/s/quizzical-danny-cr9g72?file=/src/App.js)).
