### ISSUE TITLE
[Bug]: [Tabs] Fully controlled tabs still leave a focusable element in the DOM

### ISSUE THREAD

**Issue by marinsokol5** [cloudscape-design/components#1677]
### Browser

Chrome

### Package version

v3.0.411

### React version

v18.2.0

### Description

When using Tabs component in a fully controlled manner, where a consumer controls the tab index and the tab content, the Tabs component still leaves a focusable element in the DOM, which unnecessarily bothers users interacting with the keyboard.

So I am using:
```
const [tabIndex, setTabIndex] = useState("First");
....
<Tabs
              tabs={[
                { id: "First", label: "First tab" },
                { id: "Second", label: "Second tab" }
              ]}
              onChange={(event) => setTabIndex(event.detail.activeTabId)}
 />
<Button variant="primary"> {`${tabIndex} tab selected`} </Button>
```

I get this part this focussable: 
<img width="1150" alt="Screenshot 2023-10-19 at 13 34 20" src="https://github.com/cloudscape-design/components/assets/30181549/13f2f2b9-4416-47ce-85ef-1fa3ef28eccb">

It's even worse if one uses `disableContentPaddings` as then it becomes:
<img width="1136" alt="Screenshot 2023-10-19 at 13 35 52" src="https://github.com/cloudscape-design/components/assets/30181549/9b2c10e7-753a-4a0e-ad0b-230da872cef7">

Underlying problem is that there is still a Tabs content wrapper element with a tabindex of 0.

If this component supports not having content in the Tabs, which I think is a great design choice as it unblocks many integration paths, then you need to also get rid of this wrapper. 

### Source code

* Relevant code is in https://github.com/cloudscape-design/components/blob/main/src/tabs/index.tsx#L54-L75

### Reproduction

https://codesandbox.io/s/quizzical-darkness-nchqgm?file=/src/App.js

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
In the tabs component, the `content` property is required for each tab (there are design reasons for it, even if the typings suggest otherwise).

I would recommend to use this property accordingly. If you cannot do this for some reasons (for example, if you want to preserve internal state when switching tabs), you need to build a custom component, because it is not a use-case for our tabs.
