### ISSUE TITLE
[Bug]: File Upload not working

### ISSUE THREAD

**Issue by davetbo-amzn** [cloudscape-design/components#1678]
### Browser

Firefox

### Package version

3.0.382

### React version

18.2.0

### Description

When using file upload, onChange event is sending an empty file list to the onChange handler.

### Source code

`
import { useState } from 'react';
import {  Button, Container, FileUpload , Form, FormField , SpaceBetween } from '@cloudscape-design/components';

function FileUploadForm() {
  const [filesVal, setFilesVal] = useState([]);

  function updateFilesVal(values) {
    console.log("updateFilesVal got values " + JSON.stringify(values));
    setFilesVal(values)
    console.log("filesVal is now " + JSON.stringify(values));
  }

  return (
      <form onSubmit={e => {
        sendData(e)
        e.preventDefault();
      }}>
        <Form className="testForm"
          actions={
            <SpaceBetween direction="horizontal" size="xs">
              <Button href='#/document-collections' formAction="none" variant="link">
                Cancel
              </Button>
              <Button 
                variant="primary"
              >Submit</Button>
            </SpaceBetween>
          }        >
          <Container
            header={
              <Header variant="h2">
                Edit Document Collection
              </Header>
            }
          >
            <SpaceBetween direction="vertical" size="l">
              <FormField
                label="Upload files"      
              >      
                <FileUpload        
                  onChange={({ detail }) => updateFilesVal(detail.value)}        
                  value={filesVal}        
                  i18nStrings={{          
                    uploadButtonText: e => e ? "Choose files" : "Choose file",          
                    dropzoneText: e => e ? "Drop files to upload"  : "Drop file to upload",          
                    removeFileAriaLabel: e => `Remove file ${e + 1}`,          
                    limitShowFewer: "Show fewer files",          
                    limitShowMore: "Show more files",         
                    errorIconAriaLabel: "Error"        
                  }}    
                  multiple     
                />    
              </FormField>
            </SpaceBetween>
          </Container>
        </Form>
      </form>
    );
}
`

### Reproduction

https://codesandbox.io/s/nifty-volhard-gq5rn3?file=/src/App.js

Expect that when onChange prints the file data it receives, it doesn't print out empty file data.:

`
updateFilesVal got values [{}] [index.js:27:25](webpack:////home/circleci/codesandbox-client/node_modules/console-feed/lib/Hook/index.js)`

`filesVal is now [{}]`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by johannes-weber** [comment]
Hi @davetbo-amzn, thanks for reaching out!
In your code you `console.log` the the JSON representation of the `File` array (given by the FileUpload's `onChange` event). It is not possible to directly convert a [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object into JSON notation ([more info on the MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description)).

When you remove the `JSON.stringify` method in your log statement, you'll see the actual `File` array in your DevTools console.

Feel free to re-open this issue if you have any further questions about.
