### ISSUE TITLE
[Bug]: Styles of PropertyFilter component

### ISSUE THREAD

**Issue by rktyt** [cloudscape-design/components#168]
### Browser

Chrome, Safari, Firefox

### Package version

3.0.22

### React version

18.2.0

### Description

The style is wrong in the free text search.
I haven't checked Edge, but it's probably the same.

<img width="392" alt="Explanatory image" src="https://user-images.githubusercontent.com/26789317/185050352-a8819df6-eae7-48ea-93fe-dd66ecbd2921.png">

Detail:

https://user-images.githubusercontent.com/26789317/185049417-30f2431e-9d21-4e50-b56d-9e84e4744e77.mov

----

It may not be a bug, but simply an unintended use.
But if that is the case, it should be mandatory to specify the choice of each property value in filteringOptions.

### Reproduction

https://codesandbox.io/s/cloudscape-property-fileter-freetext-style-bug-hvmzg6?file=/src/App.js

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by gethinwebster** [comment]
This can be fixed by providing a `filteringEmpty` property to specify the text that should be displayed when no options are available for a given property in `filteringOptions`

**Comment by rktyt** [comment]
@gethinwebster 
Thank you, I set filteringEmpty and the problem is gone.

Therefore, this issue is closed.
However, we would appreciate more samples of <https://cloudscape.design/components/property-filter/?tabId=playground>.
