### ISSUE TITLE
[Feature Request]: Make i18n available for custom namespaces

### ISSUE THREAD

**Issue by its-felix** [cloudscape-design/components#1685]
### Description

It is great how easy it is to provide i18n through the `I18nProvider`. Sadly, this only works for with built-in components.

Looking through the code, it looks like the system would have to capabilities to support custom namespaces.
I just tried to build support for a custom namespace myself and failed only because of unexported types:

```typescript
import { CustomHandler, InternalI18nContext } from '@cloudscape-design/components/i18n/context';
import React from 'react';

export interface I18nFormatArgTypes {
  header: {
    test: never;
  },
}

type StringKeyOf<T> = Extract<keyof T, string>;

export function useGw2AuthI18n<ComponentName extends StringKeyOf<I18nFormatArgTypes>>(componentName: ComponentName) {
  const { format } = React.useContext(InternalI18nContext);
  return <MessageKey extends StringKeyOf<I18nFormatArgTypes[ComponentName]>, ValueType>(
    key: MessageKey,
    provided: ValueType,
    customHandler?: CustomHandler<ValueType, I18nFormatArgTypes[ComponentName][MessageKey]>,
  ) => format('gw2auth.com-ui', componentName, key, provided, customHandler);
}
```

It would be a great addition to support custom namespaces through an exported function, for example:
```typescript
export function useI18n(namespace: string, componentName: string) { ... }
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by its-felix** [comment]
I'm using Cloudscape for a rewrite of the UI for my hobby project https://github.com/gw2auth .
I'm still very much into getting started, trying things out etc and learned about the builtin I18n support (which works great btw!).
I dived deep into it to see how it works under the hood (since I'm new to react too) and figured I could use the same for my custom components and pages. For now, I ended up adding my own `I18nProvider` which bundles both the Cloudscape and my own together, but I've taken over the structure and definition of i18nmessages much like it's done with the Cloudscape I18nProvider.

I try to provide everything in my app in both english and german at least. One example would be the subtitle of my legal page:
```ts
    legal: {
      lastUpdated: (date) => `Zuletzt aktualisiert: ${date.toLocaleDateString('de-DE')}`,
    },
```
and
```ts
    legal: {
      lastUpdated: (date) => `Last updated: ${date.toLocaleDateString('en-US')}`,
    },
```

While learning more about React in general, I figured its not super complicated to provide my own I18nProvider on top of the Cloudscape one, but it would be nice to be able to use the same provider for both Cloudscapes integrated i18n strings and my own custom ones, so that I could use the neat features like deferred loading of i18nmessages provided by cloudscape.

Looking at the code, it doesn't look like it would be complicated to add this, since the i18nmessages structure technically already allows for additional namespaces:
```ts
export const customI18nMessages: I18nProviderProps.Messages = {
  'my-custom-namespace': {
    en: {},
    de: {},
  },
  '@cloudscape-design/components': {
    en: {},
    de: {},
  },
};
```

From my limited research, all it seems to be missing an "accessor" of the i18n context to be exported like mentioned in the original message. Though I could understand if you'd want to keep this as an internal system to keep the flexibility internally.

**Comment by just-boris** [comment]
Our I18nProvider is for internal consumption only. To handle your own translations, you can use any other 3rd party library, such as [react-intl](https://formatjs.io/docs/react-intl/) or [react-i18next](https://react.i18next.com/) or any other
