### ISSUE TITLE
[Bug]: Popover misaligned when trigger component too close to edge of screen

### ISSUE THREAD

**Issue by marinsokol5** [cloudscape-design/components#1719]
### Browser

Chrome

### Package version

v3.0.428

### Description

I expect Popover to be properly aligned with the trigger component, but it is misaligned when trigger component is too close to end of the screen. 

Too much on the right:  
<img width="719" alt="Screenshot 2023-11-07 at 14 31 56" src="https://github.com/cloudscape-design/components/assets/30181549/2c2f7f24-4639-47c0-9fca-4335611f41b8">

Too much on the left: 
<img width="707" alt="Screenshot 2023-11-07 at 14 33 31" src="https://github.com/cloudscape-design/components/assets/30181549/74d372f2-1d22-46c2-a15a-b494b6e02014">

Just perfectly placed in the middle: 
<img width="717" alt="Screenshot 2023-11-07 at 14 33 41" src="https://github.com/cloudscape-design/components/assets/30181549/db8afa23-8109-4a71-8b00-c5fbfad33279">

You can play with this code in https://codesandbox.io/s/sweet-easley-tygr85?file=/src/App.jsx 
It's just a copy button from https://cloudscape.design/components/copy-to-clipboard/  positioned on a page.

### Source code

https://codesandbox.io/s/sweet-easley-tygr85?file=/src/App.jsx 

### Reproduction

https://codesandbox.io/s/sweet-easley-tygr85?file=/src/App.jsx 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
Summary from the DM discussion. The issue happens even if popover is far enough from screen edge to fit correctly.

This is unexpected behavior
