### ISSUE TITLE
[Bug]: useStableCallback is not in component-toolkit/internal

### ISSUE THREAD

**Issue by Avarios** [cloudscape-design/components#1736]
### Browser

Chrome

### Package version

3.0.441

### React version

18.2.0

### Description

After installing the latest Version of Cloudscape in my react vite app i get an error within the Lib:

No matching export in "node_modules/@cloudscape-design/component-toolkit/lib/internal/index.js" for import "useStableCallback"

    node_modules/@cloudscape-design/components/tag-editor/index.js:20:9:
      20 │ import { useStableCallback } from '@cloudscape-design/component-toolkit/internal';

When i take a look into the folder /component-toolkit/internal' there is only a manifest.json file.

I am using Typescript

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
Seems like a duplicate of this issue: https://github.com/cloudscape-design/components/issues/1595

Try running `npm upgrade` and check if it works

**Comment by Avarios** [comment]
> Seems like a duplicate of this issue: #1595
> 
> Try running `npm upgrade` and check if it works

Funny i even deleted my node_modules folder.
