### ISSUE TITLE
[Feature Request]: collections preferences: option to remove drag handle from non select items

### ISSUE THREAD

**Issue by alaffont21** [cloudscape-design/components#1796]
### Description

When dragging is enabled in collections preference page, it would be helpful if you could remove drag handles from elements  that aren't selected. Reordering items in preferences is useful to reorder columns imo and could add another use case to changing order of columns.

cheers

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by alaffont21** [comment]
customPreference might support this.

**Comment by Al-Dani** [comment]
Hi,
Thank you for reaching out!

Do I understand correctly, that for example here "Price class" and "Origin" shouldn't have drag handles next to it? 
![image](https://github.com/cloudscape-design/components/assets/29692746/abcb9c6f-af70-4ead-8f6b-de039acf88d4)

Could you elaborate more on why you need this behaviour?
