### ISSUE TITLE
[Bug]: Bar chart popover not shown inside modal component

### ISSUE THREAD

**Issue by naveen8801** [cloudscape-design/components#1799]
### Browser

Edge

### Package version

3.0.456

### React version

18.2.0

### Description

I want to use a Stacked bar chart inside a modal. 
Normally, popover is coming fine when hovered over on a bar but inside a modal popover is not coming up. ( Maybe it's coming up but with a z-index less then modal container that's why not visible )

### Reproduction

Please check this [Codesandbox](https://codesandbox.io/p/sandbox/damp-breeze-qyzsg4?file=%2Fsrc%2FApp.js%3A22%2C9-112%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq20279200073p6g6oo71sxd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq20279200033p6gfhuywb9l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq20279200043p6gh7hz8159%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq20279200063p6gl7km40u3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq20279200033p6gfhuywb9l%2522%253A%257B%2522id%2522%253A%2522clq20279200033p6gfhuywb9l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq20brmy00023p6gqo97xjak%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A22%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A112%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq20brmy00023p6gqo97xjak%2522%257D%252C%2522clq20279200063p6gl7km40u3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq20279200053p6gdfblnh7j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq20279200063p6gl7km40u3%2522%252C%2522activeTabId%2522%253A%2522clq20279200053p6gdfblnh7j%2522%257D%252C%2522clq20279200043p6gh7hz8159%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq20279200043p6gh7hz8159%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A14.418604651162795%257D) Link

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by Al-Dani** [comment]
hello!
Thank you for the report, we are looking into.

Could you share also if it used to work for you before?

**Comment by naveen8801** [comment]
Hi @Al-Dani, this is my first time using any chart inside the modal component.

**Comment by amanx123** [comment]
Is this issue resolved , I want to try and fix this.

**Comment by Al-Dani** [comment]
Hi @amanx123,
No, it hasn't been resolved yet

**Comment by YueyingLu** [comment]
Hi @amanx123 ,
the issue has been fixed now.
