### ISSUE TITLE
[Feature Request]: Option for App Layout to wrap content, not require it as props

### ISSUE THREAD

**Issue by rexwreyes** [cloudscape-design/components#1810]
### Description

I  recently got handed a project that requires me to use Cloudscape. Normally i use NextJS' App router but the way layout.tsx works is you use { children }, and wrap it with your 'App Layout'.  Other libraries i have used (my favorite being mantine) have variations of App Layout in which it's very easy to use in the layout.tsx file but Cloudscape's version has you enter the page content through props.  I see where this makes sense for components like carousels as all the content will be json from an api.  For a App Layout component which you intend to wrap your whole site, i feel like you need it to be more flexible than this.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by Al-Dani** [comment]
Hello,
Current interface of the App layout shouldn't be an issue in the described use-case.
You can create a wrapper around App layout  that accepts children in the default slot and passes them over to the content slot of an app layout:

```
function LayoutWrapper(props) {
  ....
  return (
     <AppLayout
        ....
        content={props.children}
      />
   )
}
```

And use it as described:
```
// layout or layout.client
...
  return (
     <LayoutWrapper>
        <MyContent/>
    </LayoutWrapper>
)
```

**Comment by rexwreyes** [comment]
Wow, I was so close.  I tried it like this and it didn't work:

`function LayoutWrapper(children) {
  ....
  return (
     <AppLayout
        ....
        content={children}
      />
   )
}`

Thanks so much!
