### ISSUE TITLE
[Feature Request]: For unintended property combinations that can be determined at runtime

### ISSUE THREAD

**Issue by rktyt** [cloudscape-design/components#182]
### Description

I suspect that a careful reading of the documentation would reveal much, but since I can't spare the time to do so, I'm going to
I would like the console to output warnings for things that cannot be covered by the type definitions.

To quickly identify issues such as the following issue.
https://github.com/cloudscape-design/components/issues/168

I think it would be better to make filteringEmpty property mandatory for the 168 issue, since it is reproduced by the "All properties" filter in the Playground of the documentation.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by taheramr** [comment]
Thanks for bringing our attention there. Typically we rely on typescript typings to validate correct use of our API. Unfortunately, here we cannot express the requirements with type definitions. Currently we keep the behaviour as-is, but may reconsider this in future, if there will be more reoccurring instances of this particular issue (#169
