### ISSUE TITLE
[Bug]: useTopNavigation causes layout thrashing

### ISSUE THREAD

**Issue by schontz** [cloudscape-design/components#1824]
### Package version

1

### React version

17

### Description

I was using a site that was slow, so I profiled it and found all sorts of force layout calls from top navigation. Source led me to this: https://github.com/cloudscape-design/components/blob/main/src/top-navigation/use-top-navigation.ts#L82

Please read: [What forces layout/reflow. The comprehensive list.](https://gist.github.com/paulirish/5d52fb081b3570c81e3a)

I found some other issues with icons and whatnot, but I'll leave that exercise up to you. When your UI library is your perf bottleneck, that's a bad place to be in. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by connorlanigan** [comment]
Hi,
I've unfortunately not been able to reproduce this yet. Can you provide more details about the issue you're seeing and how to reproduce it? Especially helpful would be a link to a page where you're encountering the performance issues, and the interactions that you do on the page that trigger the slowness.

**Comment by connorlanigan** [comment]
@schontz and I have discussed this topic directly, closing this issue for now.
