### ISSUE TITLE
[Feature Request]: Table - Group rows

### ISSUE THREAD

**Issue by Robyt96** [cloudscape-design/components#1829]
### Description

Hi, it would be nice to have a feature in the Table component to group rows together and have buttons to expand or compress groups. To give an example, I mean something like the AWS RDS Databases table:

![image](https://github.com/cloudscape-design/components/assets/35233001/8771d452-4628-4d20-b83c-9a8c72bbb258)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by connorlanigan** [comment]
Hi, thank you for reaching out. We currently don't have concrete plans for building such a feature, but it is a reasonable request. We'll keep this ticket open and update it if/when we implement that feature.

**Comment by katiegeorge** [comment]
Hi! We just released this feature, called expandable rows, a few weeks ago. Check out the [demo here](https://cloudscape.design/examples/react/table-expandable.html), which also links to the source code. We also wrote up [an article](https://cloudscape.design/patterns/resource-management/view/table-with-expandable-rows) to help you understand the choices behind the design. Hopefully this helps!

<img width="1283" alt="image" src="https://github.com/cloudscape-design/components/assets/9701338/3446aa25-c912-4c6c-ad04-1b5df46a9e75">

**Comment by Robyt96** [comment]
Wow, this looks nice, great job!

Thank you
