### ISSUE TITLE
[Bug]: Tabs - Rendering warning "Prop `aria-controls` did not match." in Next.js v14

### ISSUE THREAD

**Issue by xbeaulac** [cloudscape-design/components#1834]
### Browser

Chrome

### Package version

^3.0.466

### React version

^18

### Description

Actual behavior:
<img width="1300" alt="Screenshot 2023-12-26 at 7 51 02 AM" src="https://github.com/cloudscape-design/components/assets/26449757/9cb88443-f3f3-4baa-8456-1ec4555b7b87">

Expected behavior:
The tabs component renders as expected. How can I get rid of this warning?

### Source code

https://github.com/xbeaulac/cloudscape-tabs-bug-reprod

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by connorlanigan** [comment]
Hi, thank you for reporting this. We've reproduced the issue and we're working on a fix.

**Comment by connorlanigan** [comment]
We have released the fix now. Please let us know if you encounter any further issues.
