### ISSUE TITLE
[Feature Request]: MultiSelect + Autosuggest - Input component that allows selecting multiple options but also adding new

### ISSUE THREAD

**Issue by Samrose-Ahmed** [cloudscape-design/components#1871]
### Description

It would be useful to have a component that is a combination of the MultiSelect and AutoSuggest, specifically that it

- allows specifying a set of options to choose from
- allows user to select multiple values
- allows entering text for a new selection if not found in options (like autosuggest)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by Samrose-Ahmed** [comment]
You can kind of use AttributeEditor for this but its kind of heavy and not compact.

**Comment by michaeldowseza** [comment]
Hello!

Thank you for your request. We currently don't have any capacity to take on a new component but you might be able to work around not suing Attribute Editor by using a combination of Autosuggest and Token Group to show the selected values which would be a bit more compact.

Kind regards,
Michael
