### ISSUE TITLE
[Feature Request]: Option to customize icon for tools drawer

### ISSUE THREAD

**Issue by azaylamba** [cloudscape-design/components#1891]
### Description

AppLayout/AppLayoutProps has tools drawer which can contain a component which opens when tools drawer is open. However there is no option to customize the icon which is displayed when tools drawer is closed.

I am using the tools drawer to have user session history records and the current icon does not represent history. Having an option to customize the icon would be helpful in such cases.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
According to our [design guidelines](https://cloudscape.design/components/app-layout/?tabId=usage) the right hand panel is reserved for info content only.

> Use the tools region to implement the [help panel](https://cloudscape.design/components/help-panel/) and the [tutorial panel](https://cloudscape.design/components/tutorial-panel/).

Because this place is only reserved for info content, the icon is hard-coded to enforce this guideline.

Perhaps for your case, you could use other panels as described in this article: https://cloudscape.design/patterns/general/secondary-panels

**Comment by azaylamba** [comment]
@just-boris Thanks for the response, I will try secondary-panels, maybe will try Drawer for my use case.

**Comment by azaylamba** [comment]
@just-boris Can you please provide an example of how to use Drawer in `AppLayout` component. It seems that `AppLayoutProps` has internal Drawer interface which is different from [Drawer](https://cloudscape.design/components/drawer/)

**Comment by just-boris** [comment]
Here we have testing page: https://github.com/cloudscape-design/components/blob/main/pages/app-layout/with-drawers.page.tsx

**Comment by azaylamba** [comment]
thanks @just-boris
