### ISSUE TITLE
[Feature Request]: Allow for custom System Tag prefix check

### ISSUE THREAD

**Issue by sjakos** [cloudscape-design/components#1921]
### Description

The Tag Editor component has a lot of built in validation, which is very convenient. Would a PR be accepted to add a parameter to the validate function for a custom system tag prefix? Currently it is hard coded to check for the AWS prefix, but I don't need to filter out that tag prefix and would like to filter on my own.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by sjakos** [comment]
This is the related line from the component: https://github.com/cloudscape-design/components/blob/fff37af70186ffe48c73d081edbace552745bd3c/src/tag-editor/validation.ts#L52C16-L52C39

**Comment by just-boris** [comment]
This component is intended for a specific AWS feature: https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging-resources.html

So all validation rules inside this component are tied to that feature.

For your use-case we have a more flexible version of the same component, you can try this one: https://cloudscape.design/components/attribute-editor/

**Comment by sjakos** [comment]
The intent for the Tag Editor makes sense. While I could rebuild the Tag Editor with the other components, I was hoping I could update the Tag Editor and not have to rebuild, the `SYSTEM_TAG_PREFIX` is the only validation rule that doesn't align with the rules I have for my project.

**Comment by just-boris** [comment]
The validation rule difference is the only one you found _currently_. Since the component is not really intended for that use I would not depend on it, so we won't accidentally break you if the upstream service changes the rules and we follow up.

**Comment by sjakos** [comment]
Makes sense, thanks.
