### ISSUE TITLE
[Bug]: Autosuggest shouldn't warn for undefined enteredTextLabel when using built-in i18n

### ISSUE THREAD

**Issue by tlindsay42** [cloudscape-design/components#1926]
### Browser

Chrome, Firefox

### Package version

v3.0.0

### React version

v18.18.2

### Description

Console warning: `[Autosuggest] A value for enteredTextLabel must be provided.` in dev mode despite using the built-in i18n feature. This creates the false impression that it should be set at the component.

References:
* https://github.com/cloudscape-design/components/blob/e2bc55cf3dc218e597beb5879bf4e408f8357d6d/src/autosuggest/internal.tsx#L89-L91
* https://github.com/cloudscape-design/component-toolkit/blob/main/src/internal/logging.ts#L8-L16

### Reproduction

* https://codesandbox.io/p/devbox/3nc4tg?embed=1&file=%2Fsrc%2FApp.jsx
* Open dev tools and the warning will pop up
  ![image](https://github.com/cloudscape-design/components/assets/11078689/a1858ddf-d7d1-4f5e-a439-c68e8b0dced1)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by timogasda** [comment]
@tlindsay42 Thanks for reporting this bug. I can reproduce this on my side as well.

Would you be interested in contributing a fix?

**Comment by tlindsay42** [comment]
Sure @timogasda. Do you have a preferred way of handling this kind of thing?

**Comment by timogasda** [comment]
@tlindsay42 You can fork this repository, open a branch where you fix the issue, and then open a Pull Request for us here. For additional information about contributing code, have a look at https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md.

**Comment by tlindsay42** [comment]
@timogasda I was looking for guidance on implementation and potential preference. I did a quick (non-exhaustive) search & visual scan of other components and couldn't find any with similar conditions. Is there a way to tell if the i18n feature is in use? Or would you be okay with removing the check?

**Comment by timogasda** [comment]
Ah, I see!

The `externalTextLabel` property gets passed down to the list options and is then eventually used here: https://github.com/cloudscape-design/components/blob/2607709e89c50b171f1cc3ec919ef2905ba9f4b0/src/autosuggest/autosuggest-option.tsx#L57. This is where it currently gets the value from any potential i18n provider.

I would suggest that we move the warning down to that `AutosuggestOption` spot where we actually use the `i18n` provider.
