### ISSUE TITLE
Consider better naming for Spinner API.

### ISSUE THREAD

**Issue by wysez** [cloudscape-design/components#1990]
### Description

Every time I am having to use the Spinner component, I _always_ find myself having to go search for the Spinner documentation because the name for the `size` variable. There is no way to quantify the distinction between `big` and `large` and this seems to be the only one-off occurrence from using the classic `s`, `m`, etc. structure for many of your other components. Thanks!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by rubencarvalho** [comment]
Hello!

Thank you for your suggestion. This naming convention is also present in the `size` property of our [Icon](https://cloudscape.design/components/icon) component, but we agree it may be ambiguous and not sufficently explicit.
Unfortunately, implementing this change would be a breaking change, as it's not backward compatible. Nevertheless, we value your feedback and will consider it carefully for the development of future APIs or eventual deprecation strategies.

Thank you again!
