### ISSUE TITLE
[Documentation]: Open source demo pages from documentation

### ISSUE THREAD

**Issue by jeffreycoe** [cloudscape-design/components#200]
### Description

I wasn't sure if I missed it, but after reviewing the documentation and the demo pages, I didn't find the source code to the demo pages for each component. 

Would it be possible to open source the demo pages so the community would be able to review the example code and how each component is implemented in more detail?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by taheramr** [comment]
Hello Jeffrey, there is a similar [discussion](https://github.com/cloudscape-design/components/discussions/61) here, closing this because it is a duplicate.
