### ISSUE TITLE
[Feature Request]: Fix side navigation button positioning on iPad

### ISSUE THREAD

**Issue by rinkaaan** [cloudscape-design/components#2008]
### Description

The icon and the white circle outline are not properly centered in the left and right navigation menus on iPad. Attached screenshot. This is the newest iPad mini in portrait mode.

![Cloudscape Demos - Table view with inline editing jpeg](https://github.com/cloudscape-design/components/assets/137611486/64149437-185c-4e45-9b20-c66091788c0b)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by jperals** [comment]
Hi @rinkaaan, thanks for reporting this. Handling it in #2009.
