### ISSUE TITLE
[Feature Request]: support for framework/client routing

### ISSUE THREAD

**Issue by jxdp** [cloudscape-design/components#2020]
### Description

Really enjoying using this design system--the components look and feel fantastic. One gripe, though, is that all routing is done via anchor tags, which means full page reloads and no client-side routing support.

The benefits of client-routing are well known and are enumerated at length elsewhere--I don't want to repeat those arguments here, but I do want to emphasize that client-routing is a much better customer experience when it is available, especially for JavaScript heavy use-cases like the sort of interactive dashboards that this design-system is primarily targeting.

There is a discussion (https://github.com/cloudscape-design/components/discussions/621) that suggests using `onFollow` to support client-side navigation in the `Breadcrumbs` component.  This approach is not available in the Navigation components, and I don't think it is an approach that extends well in general as it becomes difficult to reason about (if I have a `href`, `onClick` and `onFollow`, it's no very obvious what I should expect to happen).

Most React sites/web-apps are using a framework that supports client-routing and has a framework-specific `Link` component that handles it.  So long as these components implement the `<a>` interface, they can be considered drop-in replacements for `<a>`.  

What I hope for in creating this issue is that we can find a way to add support for framework-specific routing to this amazing set of components.  Ideally this could be done in a way that is backwards-compatible with no breaking changes.

One way to achieve this would be by adding a new prop to components that render links, e.g. a `LinkComponent` prop, which would accept a component that is compatible with `<a>`.  Usage could look something like this, for example:

```js
// this example uses the NextJS link, but it could be any component with an interface compatible with <a>

import NextLink from "next/link";

// OPTION 1: opt-in individual links

<SideNavigation
  activeHref={activeHref}
  items={[
    {
      // use client-routing
      type: "link",
      href: "/something",
      text: "Something",
      LinkComponent: NextLink,
    },
    {
      // use default routing
      type: "link",
      href: "/something-else",
      text: "Something Else",
    },
  ]}
/>

// OPTION 2: opt-in all links by default

<SideNavigation
  activeHref={activeHref}
  LinkComponent={NextLink}
  items={[
    {
      // will inherit the LinkComponent prop automatically, if specified
      type: "link",
      href: "/something",
      text: "Something",
      //  LinkComponent: NextLink,  // set automatically
    },
  ]}
/>
```

The main drawback to this approach is that it isn't very extensible.  In the same spirit, you could use a slightly more complex API, like:

```js
<SideNavigation
  activeHref={activeHref}
  slots={{
    link: NextLink,
  }} // this is a more extensible API since it allows for adding more overrides without new props
  items={[
    {
      type: "link",
      href: "/something",
      text: "Something",
      //  slots: {
      //    link: NextLink,  // will be set automatically
      //  },
    },
  ]}
/>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by jperals** [comment]
Hi,

Thank you for your detailed request! While I see how such proposals could potentially make the API a bit more idiomatic, note that Side Navigation does offer an `onFollow` callback as well ([docs](https://cloudscape.design/components/side-navigation/?tabId=api#events)). Would this cover your current needs at the moment?

**Comment by jperals** [comment]
This request is actually already covered in #126. I will close this issue and suggest to continue the discussion there if you have more concerns. But I also think that @just-boris brings an important point [here](https://github.com/cloudscape-design/components/issues/126#issuecomment-1850563661) —using custom link components would break the link styles in the component.
