### ISSUE TITLE
[Feature Request]: Space between - add wrap props

### ISSUE THREAD

**Issue by AlexSKuznetsov** [cloudscape-design/components#2099]
### Description

By default "Space between" component for "horizontal" direction has "flex-wrap: wrap" css value.
But sometimes we need explicit to have "nowrap" value for "flex-wrap" property.
It will be great if you add addition prop for Space between component to modify "flex-wrap" value.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by connorlanigan** [comment]
Hello, thank you for reaching out. Can you tell us more about your use case for this? In what case do you want to disable the wrapping? (There are potentially other components that would fit, such as [the Grid component](https://refresh.cloudscape.aws.dev/components/grid))

**Comment by AlexSKuznetsov** [comment]
Hi, I'm using SpaceBetween component in a table column like this.

```js
       <SpaceBetween size="xs" direction="horizontal" alignItems="center">
          {item.status === 'Blocked' && (
            <BlockedIcon height={16} width={16} className={style.icon} />
          )}
          <Box
            fontSize="body-m"
            color={
              item.status === 'Blocked'
                ? 'text-status-error'
                : 'text-body-secondary'
            }
          >
            {item.status}
          </Box>
        </SpaceBetween>
`

**Comment by connorlanigan** [comment]
From your code snippet, it looks similar to [our StatusIndicator component](https://cloudscape.design/components/status-indicator/). The StatusIndicator handles all wrapping out-of-the-box:
![status_indicator](https://github.com/cloudscape-design/components/assets/9086585/e752abad-c2e2-4ad5-af19-3d28a2634c9b)

You can also see in our demos how we use the StatusIndicator in a Table column: https://cloudscape.design/examples/react/table.html
![table_with_status_indicator](https://github.com/cloudscape-design/components/assets/9086585/0582eeb4-901f-421d-8ce5-476dd96ae491)


Would that be an option for you to use?

**Comment by AlexSKuznetsov** [comment]
Status indicator doesn't provide option for the custom Icon but we have a custom Icon here.
If Status indicator will provide api for custom icon it will help also.

**Comment by connorlanigan** [comment]
I've discussed your request with the team. We'd recommend that you remove the SpaceBetween, and use the browser's regular inline layout with a space character instead:
```tsx
<div>
  <Icon name="star" variant="error" />{" "}
  <Box fontSize="body-m" color="text-status-error" display="inline">
    Blocked
  </Box>
</div>
```
![example](https://github.com/cloudscape-design/components/assets/9086585/373a4feb-a4d3-407f-bf7b-7bd7ef8aaf79)

The SpaceBetween component is intended for laying out blocks of content (for example, multiple Buttons), not for regular inline content such as text.

**Comment by AlexSKuznetsov** [comment]
That what I talking about. 
I need to wrap my component into div and add classname with 'nowrap'.
I thought that since Space between component having Flex attribute it will convenient to add 'no-wrap' props to it.
