### ISSUE TITLE
[Bug]: findDrawersTriggers returns empty array if more than one drawer is in AppLayout

### ISSUE THREAD

**Issue by 9bits** [cloudscape-design/components#2105]
### Package version

Release 3.0.593

### React version

18.2.0

### Problem 
When more than one drawer is added AppLayout, an unexpected behavior occurs when writing unit tests for the component.

### Expected
1. Adding 2 drawer items to AppLayout should result in findDrawersTriggers returning an array of 2 drawer triggers.

### Steps:
1. Add 2 drawer items to AppLayout under the `drawers` property
2. Write a unit test that uses `findDrawersTriggers`. Observe that `findDrawersTriggers` returns an empty array.
3. Remove 1 drawer item so that there is only 1 drawer item in AppLayout in the `drawers` property.
4. Run the same unit test, and observe that `findDrawersTriggers` now returns a non-empty array.

### Example that will cause `findDrawersTriggers` to fail
```
<AppLayout
  content={<ContentLayout disableOverlap></ContentLayout>}
  contentType="table"
  headerSelector={`#${APP_TOP_NAVIGATION_ID}`}
  navigationOpen={isNavigationOpen}
  splitPanelOpen={isSplitPanelOpen}
  navigation={<Navigation />}
  splitPanel={<SomeSplitPanelComponent />}
  splitPanelPreferences={{ position: "side" }}
  drawers={[
    {
      id: DRAWER_ID_1,
      content: <SomeComponent />,
      trigger: {
        iconName: "user-profile",
      },
      ariaLabels: {
        drawerName: DRAWER_ID_1,
      },
      resizable: true,
      defaultSize: DEFAULT_PANEL_SIZE,
    },
    {
      id: DRAWER_ID_2,
      content: <SomeOtherComponent />,
      trigger: {
        iconName: "contact",
      },
      ariaLabels: {
        drawerName: DRAWER_ID_2,
      },
      resizable: true,
      defaultSize: DEFAULT_PANEL_SIZE,
    },
  ]}
  activeDrawerId={DRAWER_ID_1}
  notifications={<Flashbar items={notificationsState} />}
  onNavigationChange={(event) => setIsNavigationOpen(event.detail.open)}
  onSplitPanelToggle={(event) => setIsSplitPanelOpen(event.detail.open)}
  onDrawerChange={(event) => setActiveDrawerId(event.detail.activeDrawerId)}
  onSplitPanelPreferencesChange={() => {}}
/>;

```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
Do you use JSDOM?  It probably does not find any drawers because they wrapped into the overflow menu:
<img width="195" alt="image" src="https://github.com/cloudscape-design/components/assets/812240/b3b702bf-38ee-4962-ae53-c7f02f1c4898">

**Comment by just-boris** [comment]
Resolved in https://github.com/cloudscape-design/components/pull/2112
