### ISSUE TITLE
[Feature Request]: update css class naming prefix 

### ISSUE THREAD

**Issue by square-li** [cloudscape-design/components#228]
### Description

Current classnames are prefixed with `awsui_`.  For example,
``` jsx
import * as React from "react";
import Box from "@cloudscape-design/components/box";

export default () => {
  return <Box variant="p">text</Box>;
}
``` 
will be rendered as 
```html
<p class="awsui_root_18wu0_1xtkt_93 awsui_box_18wu0_1xtkt_205 awsui_p-variant_18wu0_1xtkt_205 awsui_color-default_18wu0_1xtkt_205 awsui_font-size-default_18wu0_1xtkt_221 awsui_font-weight-default_18wu0_1xtkt_261">text</p>
```

As the lib is not called `awsui`, maybe changing the prefix to something like`cloudscape_design` or `cs_`?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by abdhalees** [comment]
Hello Bill, 

This change would be backward incompatible with earlier versions as these classes are used by consumers for integration testing. 
also we don't consider this information "awsui" as private so we're okay with exposing it in the library's internal implementation

**Comment by square-li** [comment]
Right that makes sense. Thanks for the explanation.
