### ISSUE TITLE
[Bug]: Build Error

### ISSUE THREAD

**Issue by hadinasser0** [cloudscape-design/components#2339]
### Browser

Chrome

### Package version

@cloudscape-design/board-components: "^3.0.60",
@cloudscape-design/collection-hooks: "^1.0.45",
@cloudscape-design/components: "^3.0.628",
@cloudscape-design/global-styles: "^1.0.27",

### React version

18.2.0

### Description

Hello, I am trying to build my react application, but I am getting error 

`Failed to compile.
#9 242.1
#9 242.1 Lexical error on line 1: Unrecognized text.
#9 242.1   Erroneous area:
#9 242.1 1: 100% - var(--space-grid-gutter-ieqn7e, 20px);
#9 242.1 ^..............................................^
#9 242.1 2:   max-inline-size: calc(100% - var(--space-grid-gutter-ieqn7e, 20px));
#9 242.1 3: }
#9 242.1 CompileError: Begins at CSS selector undefined`

It was working fine until suddenly I started experiencing this error without updating versions,
I looked inside the package and it seems this code is inside the CSS file for Tiles components, but sill the error is not clear to debug and fix

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by jperals** [comment]
Hi, 

- Which tools and which versions are you using to build your project?
- Which version of Cloudscape?
- Did you do any changes to your dependencies or your code that could have led to this error?

**Comment by gethinwebster** [comment]
In case it helps, others have been able to resolve this by upgrading from old versions of `react-scripts` to something more recent, if you're using that. Closing for now, let us know if you have any further problems.
