### ISSUE TITLE
[Bug]: Cannot import HeaderProps.Variant

### ISSUE THREAD

**Issue by tbelmega** [cloudscape-design/components#241]
### Package version

3.0.39

### Description

I want to create a function and pass Header Variant as well as Table Variant as parameters:
```
import {TableProps, HeaderProps} from "@cloudscape-design/components";
function createTable(
  headerVariant: HeaderProps.Variant,
  tableVariant: TableProps.Variant,
  ...
```

Using TableProps.Variant works fine, HeaderProps.Variant results in a type error.
The reason is that table.interfaces.d.ts exports the namespace TableProps, while header/interfaces.d.ts only declares the namespace HeaderProps and doesn't export it.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by abdhalees** [comment]
Hello Thiemo, 

thanks for the report, we'll work on a fix.
