### ISSUE TITLE
[Bug]: Drag and drop to upload a file does not work on macOS Safari

### ISSUE THREAD

**Issue by rinkaaan** [cloudscape-design/components#2427]
### Browser

Safari

### Package version

3.0.662

### React version

18.3.1

### Description

Drag and drop to upload works on Chrome but not on Safari on macOS.
Sonoma 14.5, Safari 17.5.
https://cloudscape.design/components/file-upload
Only click to upload via system dialog works.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by johannes-weber** [comment]
Hi @rinkaaan, thanks for reaching out.
I was able to reproduce the issue on Safari 17, (macOS 13.6.7). We're taking a look at it.

**Comment by johannes-weber** [comment]
Closing this issue - resolved in https://github.com/cloudscape-design/components/pull/2444
