### ISSUE TITLE
[Bug]: Gap between files missing on Safari

### ISSUE THREAD

**Issue by rinkaaan** [cloudscape-design/components#2433]
### Browser

Safari (iOS and macOS)

### Package version

3.0.671

### React version

18.3.1

### Description

Gap between files missing on Safari sometimes when uploading multiple images with thumbnail previews.

https://cloudscape.design/components/file-upload?tabId=playground&example=multiple-files-upload

<img width="1624" alt="Screenshot 2024-06-29 at 12 46 13 PM" src="https://github.com/cloudscape-design/components/assets/137611486/708dc02a-0fd0-4f85-a455-249a4be8f3a9">

### Source code

Test image: https://pics.craiyon.com/2023-10-31/bf8410c49c054d9faa5673cd89b6818a.webp

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by johannes-weber** [comment]
Hi rinkaaan, thanks for reporting, we're taking a look at and keep this bug report updated about.
