### ISSUE TITLE
[Bug]: Missing "./internal/analytics-metadata" specifier in "@cloudscape-design/component-toolkit" package after upgrading from 3.0.684

### ISSUE THREAD

**Issue by hackf5** [cloudscape-design/components#2555]
### Package version

3.0.708

### React version

18.3.1

### Description

Running through Vite, after upgrading from 3.0.684 I get the error:

 Missing "./internal/analytics-metadata" specifier in "@cloudscape-design/component-toolkit" package [plugin vite:dep-pre-bundle]
@repo/admin:dev:
@repo/admin:dev:     ../../node_modules/@cloudscape-design/components/table/body-cell/td-element.js:6:47:
@repo/admin:dev:       6 │ ...{ copyAnalyticsMetadataAttribute } from '@cloudscape-design/component-toolkit/internal/analytics-metadata';
@repo/admin:dev:         ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@repo/admin:dev:
@repo/admin:dev:   This error came from the "onResolve" callback registered here:
@repo/admin:dev:
@repo/admin:dev:     ../../node_modules/esbuild/lib/main.js:1150:20:
@repo/admin:dev:       1150 │       let promise = setup({
@repo/admin:dev:            ╵                     ^
@repo/admin:dev:
@repo/admin:dev:     at setup (file:///node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:46835:13)
@repo/admin:dev:     at handlePlugins (/node_modules/esbuild/lib/main.js:1150:21)
@repo/admin:dev:     at buildOrContextImpl (/node_modules/esbuild/lib/main.js:873:5)
@repo/admin:dev:     at Object.buildOrContext (/node_modules/esbuild/lib/main.js:699:5)
@repo/admin:dev:     at /node_modules/esbuild/lib/main.js:2032:68
@repo/admin:dev:     at new Promise (<anonymous>)
@repo/admin:dev:     at Object.context (/node_modules/esbuild/lib/main.js:2032:27)
@repo/admin:dev:     at Object.context (/node_modules/esbuild/lib/main.js:1874:58)
@repo/admin:dev:     at prepareEsbuildOptimizerRun (file:///node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:50792:33)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by pan-kot** [comment]
Hello,

The issue is likely due to versions mismatch between dependant Cloudscape libraries, see similar issues: https://github.com/cloudscape-design/components/issues?q=is%3Aissue+toolkit+

Cleaning package-lock and reinstalling dependencies usually helps in such cases.

**Comment by hackf5** [comment]
I deleted `yarn.lock` and `node_modules` upgraded and then ran `yarn install` and everything works now.

Thanks for your help.
