### ISSUE TITLE
[Feature Request]: Multiselect "Select all" Option

### ISSUE THREAD

**Issue by tbelmega** [cloudscape-design/components#259]
### Description

Hi friends,

we are using the Multiselect component and we'd like to offer a "select all" option. Here is an example for clarification:
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/9363470/189358157-be7f0019-c6a8-45a3-af46-66440867c6e5.png">
I'm aware I can build it into each usage of Multiselect,by adding an extra special item to the items list and than handle the special case in the onChange function, but it's a bit clunky and repetitive. Would be awesome to have a built-in option in the Multiselect component to enable/disable a "Select all".

I'm happy to implement it and create a pull request if you want me to.

Best regards
Thiemo

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by connorlanigan** [comment]
Hello Thiemo,

the Multiselect component provides an option to define groups of items, which can then be selected/unselected together using a single checkbox. You can see an example of this in [the _"With groups"_ example of the component's page](https://cloudscape.design/components/multiselect/?tabId=playground&example=with-groups).

In your case, you could use this to define a single group (e.g. "All regions") that contains all the items.

**Comment by tbelmega** [comment]
Wow, that's awesome. I didn't realize that. Thank you!
