### ISSUE TITLE
[Bug]: ContentLayout is not exported

### ISSUE THREAD

**Issue by athermantis** [cloudscape-design/components#263]
### Browser

Chrome

### Package version

3.0.1

### React version

18.2

### Description

Documentation shows a component ContentLayout (https://cloudscape.design/components/content-layout/?tabId=playground), but this is not exported from the package. 

### Reproduction

attempt to import ContentLayout component into react

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by connorlanigan** [comment]
Hello,
the package version you indicated (`3.0.1`) is out of date and does not contain the new ContentLayout component. Please upgrade to the current version (`3.0.53`).

**Comment by athermantis** [comment]
Thank you!!
