### ISSUE TITLE
[Bug]: Modal border radius changes if there is form field

### ISSUE THREAD

**Issue by phuctm97** [cloudscape-design/components#2641]
### Browser

Safari

### Package version

3.0.733

### React version

18.3.1

### Description

When a Modal contains a FormField with Input, the modal border radius changes from 0 to rounded when opening.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by YueyingLu** [comment]
Hi @phuctm97 
could you share how I can reproduce the issue you report? https://cloudscape.design/components/modal/?tabId=playground&example=with-text-input

**Comment by phuctm97** [comment]
> Hi @phuctm97 could you share how I can reproduce the issue you report? https://cloudscape.design/components/modal/?tabId=playground&example=with-text-input

Just open the link above and click on "Open modal", you'll see that the modal border radius starts being rectangular then rounded for half a second each time.

https://github.com/user-attachments/assets/cbb1749f-f8de-4f32-a4af-c57b5e0cbeab

**Comment by taheramr** [comment]
I can't reproduce this and I can't clearly see the difference in the video. Can you provide screenshots pointing out the bug ?

**Comment by phuctm97** [comment]
I think the bug is fixed.
