### ISSUE TITLE
[Feature Request]: Draggable rows in table component

### ISSUE THREAD

**Issue by BrunoPM2001** [cloudscape-design/components#2658]
### Description

Would be amazing if the table component had the option to reorder the rows (something similar to the options in CollectionPreferences component).
![sample](https://github.com/user-attachments/assets/903fff63-c8ed-4118-86c4-4a55d83ec3ea)
Maybe the feature could be added just when other options are not in use, like pagination or expandable rows (it wouldn't have sense in that use cases).

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by Al-Dani** [comment]
Hello,
thank you for reaching out.

Adding an ability to re-order table rows does seem like a sensible addition to the system, we have this on our radar. However we don’t have plans for making this change at the moment.

I will keep this issue open to collect any additional feedback or use cases.

Thanks!
