### ISSUE TITLE
Make it possible to limit CodeView height and have content be scrollable.

### ISSUE THREAD

**Issue by Bergmam** [cloudscape-design/components#2770]
### Description

I want to display some JSON data in a CodeView, but as my JSON can get quite large it would be nice to be able to limit the height of the component and have the content be scrollable.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by johannes-weber** [comment]
Hello @Bergmam, thanks for reaching out!
You can handle that on your side by wrapping the CodeView component with an element which has defined a min-height and makes the overflow scrollable.
