### ISSUE TITLE
[Documentation]: Please, update Figma design components

### ISSUE THREAD

**Issue by AlexSKuznetsov** [cloudscape-design/components#2803]
### Description

[This page](https://cloudscape.design/get-started/resources/design-resources/) pointing to Figma with outdated components. Components library last time update was 2 years ago.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by at-susie** [comment]
Hi @AlexSKuznetsov!

Thanks for reaching out. We plan to update the Figma libraries with all recent changes by the end of 2024.

Best,
Atsushi

**Comment by stockarea** [comment]
When are we updating the components?

**Comment by at-susie** [comment]
Hi @AlexSKuznetsov, @stockarea!

We've finally released [the new version of Cloudscape Figma library](https://www.figma.com/community/file/1448695453848536664). 

Discover the latest enhancements with variable-based styling, updated Cloudscape components optimized for information density, and enhanced file performance. Seamlessly switch between light and dark modes, and explore advanced theming capabilities.
