### ISSUE TITLE
[Bug]: Backward incompatibility on use of `label` in CollectionPreferences.

### ISSUE THREAD

**Issue by nicklera1** [cloudscape-design/components#2857]
### Browser

Chrome, Safari, Firefox, Edge

### Package version

v3.0.782

### React version

18.1

### Description

Resent change to https://github.com/cloudscape-design/components/commit/a5defd9e11e92cbe126a6093da15c80c6ba2b6c7#diff-9a4626222e43ed6f71fb6aa5a4fc8bff1727c66603314abd4888c51c55025741R65 have broke rendering of Preference panel due to new filtering logic where it assumes that label is string which is based on the interface (my assumption) 

 ```    
export interface ContentDisplayOption {
        id: string;
        label: string;
        alwaysVisible?: boolean;
    }
```

The issue is that we had use `ReactNode` as label before and since the current code assumes it's string it throws and error.
```
TypeError: e.label.toLowerCase is not a function
    at index.tsx:65:22
    at Array.filter (<anonymous>)
    at index.tsx:64:60
```

### Source code

https://github.com/cloudscape-design/components/commit/a5defd9e11e92cbe126a6093da15c80c6ba2b6c7#diff-9a4626222e43ed6f71fb6aa5a4fc8bff1727c66603314abd4888c51c55025741R65
 ```
const sortedAndFilteredOptions = useMemo(
    () =>
      getSortedOptions({ options, contentDisplay: value }).filter(option =>
        option.label.toLowerCase().trim().includes(columnFilteringText.toLowerCase().trim())
      ),
    [columnFilteringText, options, value]
  );
```

### Reproduction

```
import styled from "styled-components";
// Example of ContentDisplayOption
export interface ContentDisplayOption {
  id: string;
  label: string;
  alwaysVisible?: boolean;
}

function App() {
  const options = [
    {
      id: "first",
      label: "First Label",
      alwaysVisible: true,
    },
    {
      id: "first",
      label: (
        // ReactNode passed here
        <div>
          <strong>ALSO LABEL</strong>
        </div>
      ) as React.ReactNode,
      alwaysVisible: true,
    },
  ] as ContentDisplayOption[];
  return (
    <div style={{ padding: "30px" }}>
      {options.map((opt) => {
        return (
          <ul>
            <li> Id: {opt.id} </li>
            <li> Label: {opt.label}</li>
            <li> Visible: {opt.alwaysVisible ? "Yes" : "no"} </li>
          </ul>
        );
      })}
    </div>
  );
}

export default App;
```
[![Edit React@18-Typescript (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/react-18-typescript-gkle61)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by abdhalees** [comment]
Hi Nikolay,

per our API `label` accepts only string, there is no backward incompatible change since we didn't change the API.

your previous behaviour should still work though, you just cannot use the new filtering feature unless you follow our API and use strings for `label`

**Comment by abdhalees** [comment]
actually, we'll fix it anyway.
