### ISSUE TITLE
[Bug]: `headingTagOverride` prop not working for Expandable section having `container` variant

### ISSUE THREAD

**Issue by naveen8801** [cloudscape-design/components#3008]
### Browser

Edge

### Package version

Latest

### React version

Latest

### Description

It looks like a bug as in the [playground](https://cloudscape.design/components/expandable-section/?tabId=playground&example=container) it doesn't work.

### Reproduction

Just visit the [playground](https://cloudscape.design/components/expandable-section/?tabId=playground&example=container), set variant as `container` and try to change `headingTagOverride` prop.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by jperals** [comment]
Closing this issue. Please open a new one if you keep facing any problems.
