### ISSUE TITLE
[Bug]: Documented Badge colors do not exist in npm

### ISSUE THREAD

**Issue by dreessan** [cloudscape-design/components#3064]
### Browser

Chrome

### Package version

3.0.704

### React version

"18.2.0

### Description

Documented Badge colors are not available in latest(?) version of client

https://cloudscape.design/components/badge/
- severity-critical exists

after running `npm i @cloudscape-design/components@latest`
file at location `<project_dir>/node_modules/@cloudscape-design/components/badge` is the following

```
import React from 'react';
import { BaseComponentProps } from '../internal/base-component';
export interface BadgeProps extends BaseComponentProps {
    /**
     * Specifies the badge color.
     */
    color?: 'blue' | 'grey' | 'green' | 'red';
    /**
     * Text displayed inside the badge.
     */
    children?: React.ReactNode;
}
//# sourceMappingURL=interfaces.d.ts.map
```

This contains fewer options than documented

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by connorlanigan** [comment]
The version you're using (3.0.704) was released in August, it is not the latest version. In the current latest version (3.0.839), the `severity-critical` colour is present in the interface declaration (along with the other severity colours). I recommend deleting your local `node_modules` folder, checking that your Cloudscape dependency declaration in package.json is not pinned to any specific version or tag, and re-running `npm install`.


You can view the code of each NPM release on the NPM website in the package's "Code" tab: https://www.npmjs.com/package/@cloudscape-design/components/?activeTab=code

![image](https://github.com/user-attachments/assets/1654df04-0dea-40ef-95a0-bbe068e4582a)

**Comment by dreessan** [comment]
Ah, understood. I needed to get a version in-between ours because of npmpm and other AWS internal tooling, iykyk.

Thanks!
