### ISSUE TITLE
[Bug]: TopNavigation - onFollow event.details object is empty for identity section 

### ISSUE THREAD

**Issue by piyushpranjal03** [cloudscape-design/components#3141]
### Browser

Chrome

### Package version

3.0.833

### React version

18.2.0

### Description

TopNavigation is not working as expected. I am not sure if my understanding is correct.  

I am expecting that `followLink` function should work for both `identity` and `utilities` as both are `CancelableEventHandler`.  When I am clicking on a link available in `utilities` section it is printing the `event.details` object with expected keys but when I am clicking on the logo which is a part of `identity` section then `event.details` has no keys, it is completely empty.

<img width="1800" alt="Screenshot 2024-12-14 at 7 03 41 PM" src="https://github.com/user-attachments/assets/6af3f55e-15a9-423b-a905-701d9da30183" />

https://www.mediafire.com/file/aqsei90v781nba0/sample_cloudscape.zip/file
This is the small vite project I created. This can help you to de-bug.

Could you please check and help

### Source code

Source code is visible in the above image. 

### Reproduction

Vite project zip is attached through media fire.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by gethinwebster** [comment]
This is the expected behavior, not a bug. The details are added to events within `utilities` because there may be multiple utilities, but there is only ever one `identity` so no details are required to distinguish that event.
