### ISSUE TITLE
[Bug]: d3-color transitive dependency is vulnerable to ReDos

### ISSUE THREAD

**Issue by agdimech** [cloudscape-design/components#324]
### Browser

Chrome

### Package version

v3.0.68

### React version

v18

### Description

The d3-color module provides representations for various color spaces in the browser. Versions prior to 3.1.0 are vulnerable to a Regular expression Denial of Service. This issue has been patched in version 3.1.0. There are no known workarounds.

Cloudscape currently has a transitive dependency on `d3-scale -> d3-interpolate -> d3-color`.

It would be great if we can upgrade this to > 3.1.0

### Source code

https://github.com/cloudscape-design/components/blob/main/package.json#L35

d3-scale has a dependency on d3-color which is the culprit.

### Reproduction

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by svozza** [comment]
Also, is there a workaround while we wait for https://github.com/cloudscape-design/components/pull/325 to be merged? This is breaking our build.

**Comment by FlorianDr** [comment]
Thank you for reporting. We are working on resolving this issue. We will update this issue with updates.

**Comment by svozza** [comment]
For anyone waiting on this, assuming you're using v8.3 or above of NPM, just add the following section to your package.json:

```
"overrides": {
    "d3-scale": "4.0.2"
 }
```

**Comment by FlorianDr** [comment]
The mitigation of this issue turned to be complex, due to changes to in bundling between the two versions (CJS vs ESM). We will continue to provide updates in this issue.
