### ISSUE TITLE
[Bug]: Able to keep click next past end in Pagination with openEnd

### ISSUE THREAD

**Issue by 32teeth** [cloudscape-design/components#392]
### Package version

Current

### Description

> Component Setup

```
import * as React from "react";
import Pagination from "@amzn/awsui-components-react/polaris/pagination";

export default () => {
  const [
    currentPageIndex,
    setCurrentPageIndex
  ] = React.useState(1);
  return (
    <Pagination
      ariaLabels={{
        nextPageLabel: "Next page",
        previousPageLabel: "Previous page",
        pageLabel: pageNumber =>
          `Page ${pageNumber} of all pages`
      }}
      currentPageIndex={currentPageIndex}
      onChange={({ detail }) =>
        setCurrentPageIndex(detail.currentPageIndex)
      }
      openEnd
      pagesCount={5}
    />
  );
}
```

If i have `openEnd` i can keep clicking 'next arrow' past the end. and then have to click the 
back arrow'

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
This is expected behavior. Having the next page button enabled is what "open end" by definition means.

An expected use of `openEnd` property and state management was already discussed in another related request: https://github.com/cloudscape-design/components/pull/385#issuecomment-1282688609
