### ISSUE TITLE
Request: Add Changelog

### ISSUE THREAD

**Issue by arunim2405** [cloudscape-design/components#393]
### Description

I could not find a changelog on the documentation website or anywhere else in the repo. A CHANGELOG.MD would be very helpful.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by jpdup** [comment]
+1, when new versions are released we have no idea what changed. a CHANGELOG.MD could help use narrow down the areas in our application that we need to scrutinize.

**Comment by abdhalees** [comment]
Hello all, 

we started publishing release notes in this repository for new releases, please visit https://github.com/cloudscape-design/components/releases

I'll close this issue, feel free to reopen if you have any questions or open a new issue if you have other feature requests
