### ISSUE TITLE
[Feature Request]: Autocomplete Component

### ISSUE THREAD

**Issue by arunim2405** [cloudscape-design/components#394]
### Description

An Autocomplete component like the one MUI here https://mui.com/material-ui/react-autocomplete
Can also be achieved by giving search capability in the Select component

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by arunim2405** [comment]
Update: Found the option to set filteringType="auto" to achieve this, do we have the capability to add an option if its not there?

**Comment by arunim2405** [comment]
Or like a Freesolo option like in material ui
https://v4.mui.com/components/autocomplete/#free-solo

**Comment by just-boris** [comment]
Hello!

Did you check our autosuggest component?
https://cloudscape.design/components/autosuggest/?tabId=playground

**Comment by arunim2405** [comment]
@just-boris This was exactly what I was looking for, thank you!
