### ISSUE TITLE
[Feature Request]: i18n support

### ISSUE THREAD

**Issue by francis-jjk** [cloudscape-design/components#412]
### Description

like this https://ant.design/docs/react/i18n

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
Hello!

We have no particular plans in this regard. Currently our components expose all strings via props (typically, `i18nStrings`). You can build a similar to antd API on your end by wrapping our components.

I will keep this ticket open for future references

**Comment by just-boris** [comment]
Released this: https://cloudscape.design/get-started/dev-guides/internationalization/
