### ISSUE TITLE
[Feature Request]: Add support for react-hook-form

### ISSUE THREAD

**Issue by ab18556** [cloudscape-design/components#414]
### Description

The way the ref is used on each elements at the moment we cannot easily use react-hook-form. For component libraries, react suggest that we forward the ref. 
https://reactjs.org/docs/forwarding-refs.html

react-form-hook use the ref to bind the events on the input itself, but with the actual state of the ref it doesn't work.
https://react-hook-form.com/api/useform/register#registerRef

There is a workaround, but it makes react-form-hook less usefull and fun to work with.
https://react-hook-form.com/faqs#Whatifyoudonthaveaccesstoref

react-form-hook is a really popular library used by a lot of people. Maybe there is an other work around I am not aware of.  If this is the case I would be happy to have it.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
This can be implemented in userland

```js
import React from 'react';
import { Controller } from 'react-hook-form';
import { Input } from '@cloudscape-design/components';

export const ControlledInput = ({ name, control, ...props }) => (
  <Controller
    name={name}
    control={control}
    render={({ field: { ref, onChange, onBlur, value } }) => (
      <Input ref={ref} name={name} value={value} onBlur={onBlur} onChange={e => onChange(e.detail.value)} {...props} />
    )}
  />
);
```

You can wrap every control and publish it is a separate package

Having it built into library does not sound future proof, because what if somebody wants to use another form library

**Comment by ab18556** [comment]
I understand what you mean, but at the same time I think that Cloudscape should expose standard properties as much as possible. For example, the onChange is not providing the usual react event. It brings might bring a lot of issues other libraries aswell. If Cloudscape is about design, why is it fiddling with the events and refs? why is value required even if it is empty?

**Comment by just-boris** [comment]
What you are asking sounds as a breaking change, but we are not planning on publishing a new major version in near future.

if you have any suggestion how to change API in a non-breaking way that may help you – let us know

**Comment by just-boris** [comment]
Closing because this feature is not applicable to our project
