### ISSUE TITLE
[Enhancement]: Change text style for selected options in multiselect

### ISSUE THREAD

**Issue by arunim2405** [cloudscape-design/components#424]
### Description

The current text style for selected options in multiselect is too close to the placeholder text style in other form inputs.
Example below. Changing it to something what a filled input value looks like will make it more clearer.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/47343112/198524684-684e06aa-c8b3-4331-b251-b83a1f5b02f5.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
This looks like placeholder because it is in fact placeholder. In multiselect, selected items are below the dropdown box:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/812240/198680804-4c72457d-d72d-4dba-88b6-4114357c6748.png">
