### ISSUE TITLE
[Feature Request]: Table single select has no unselect

### ISSUE THREAD

**Issue by nicolaeClichici** [cloudscape-design/components#439]
### Description

Hello !
A Table component with ```selectionType="single"``` doesn't support unselect item like  ```selectionType="multi"```.
Example: 
1) Select item.
2) Try to unselect -> nothin happens.(onSelectionChange is not triggered by trying to unselect item)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by rubencarvalho** [comment]
Hello!
Our `selectionType="single"` Table follows the standard behaviour of a radio group which also doesn’t provide a way to unselect an item.
Could you share more information about your use case? Maybe there’s a better UX pattern we can recommend to achieve what you want to do.
Thank you.

**Comment by nicolaeClichici** [comment]
Hi!
In my case, I want to make an table with single selection and a split panel wich is related to selection item details, example: 
select an item from table -> split-panel open and show info about item -> unselect item in table -> split-panel close.

**Comment by connorlanigan** [comment]
Hello!
The split panel already provides a built-in way of closing it, by clicking the arrow icon in the top right of the split panel.
