### ISSUE TITLE
[Feature Request]: Read only code component?

### ISSUE THREAD

**Issue by nichita-pasecinic** [cloudscape-design/components#456]
### Description

changing editor configurations should be possible via `ace.editor()` returned instance (I belive you save it as a ref).

Is there any way to get this instance, or change some editor configurations, like setting the mode to read only ?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by nichita-pasecinic** [comment]
editor ref is not really necessary at this point, setting ace config is enough for now `ace.config.set('readOnly', true)`.

**Comment by nichita-pasecinic** [comment]
IDK if there would be a more advances use case where editorRef would be necessary, but I'll surrey get back here 😄 

Thanks, nice ui-kit!

**Comment by pan-kot** [comment]
Hello Nichita,

The code editor currently does not support a read-only mode, but it is on our radar. The main concern is the impact on the bundle size the code editor has. Ideally, we want the readonly variant to be lightweight.

A viable alternative four now could be, for instance, https://prismjs.com/ to bring syntax highlight to the code snippets.

**Comment by fr0stf0x** [comment]
@pan-kot @nichita-pasecinic  any updates on this?

by far my solution is prevent any `keydown` or `mousedown` events but when I press backspace or delete, the code editor still displays the changed value 

```ts
// MyCodeEditor.tsx

function preventChangeIfNeeded(event: KeyboardEvent) {
  // 'backspace' and 'delete' do not go into this
  const { target } = event;

  if (target && (target as HTMLTextAreaElement).classList.contains('ace_text-input')) {
    event.preventDefault();
    event.stopPropagation();
  }
}

function hideCursor(event: MouseEvent) {
  const cursorLayer = document.querySelector('.ace_cursor-layer');

  if (cursorLayer) {
    event.preventDefault();
    event.stopPropagation();
    (cursorLayer as HTMLDivElement).style.display = 'none';
  }
}

function MyCodeEditor({readonly}) {
// ...
  useEffect(() => {
    if (readonly) {
      window.addEventListener('keydown', preventChangeIfNeeded);
      window.addEventListener('mousedown', hideCursor);

      return () => {
        window.removeEventListener('keydown', preventChangeIfNeeded);
        window.removeEventListener('mousedown', hideCursor);
      };
    }
  }, [readonly]);
// ...
}
```

**Comment by nichita-pasecinic** [comment]
@fr0stf0x you could just change the config of the global 'Ace' instance to readOnly mode


```jsx
useEffect(() => {
    import('ace-builds').then((aceLib) => {
      aceLib.config.set('themePath', CDN);
      aceLib.config.set('basePath', CDN);
      aceLib.config.set('modePath', CDN);
      aceLib.config.set('themePath', CDN);
      aceLib.config.set('workerPath', CDN);
     // this one
      aceLib.config.set('readOnly', readOnly); 
      aceLib.config.set('showPrintMargin', false);
      setAce(aceLib);
      setLoading(false);
    });
  }, [readOnly]);
```

In my case `readOnly` is a component prop

**Comment by just-boris** [comment]
The older answer still applies: https://github.com/cloudscape-design/components/issues/456#issuecomment-1311578595

As the name suggests, code **editor** is for editable use-cases only. For read-only cases use another component. Loading Ace library for read-only use-case is a very big overkill. There are more lightweight options out there.

Updated the issue title to reflect what it really tracks (providing an official component for viewing code)

**Comment by connorlanigan** [comment]
We have recently released the CodeView component. Details and examples can be found on [the component's page on our website](https://cloudscape.design/components/code-view/).
