### ISSUE TITLE
[Bug]: Table `onRowClick` with a table cell with link

### ISSUE THREAD

**Issue by nichita-pasecinic** [cloudscape-design/components#458]
### Package version

^3.0.95

### React version

^17.0.2

### Description

Hi 👋 ,

I have a `Table` component with an `onRowClick`. The table has a cell that renders a `Link` component with an `onFollow` handler attached to it.

I need to trigger `onRowClick` only when user clicked on the cell, or outside cell, but it should NOT trigger when user clicked on the `Link`

`event.preventDefault()` from the `onFollow` does not help much.

Is that even possible ? (to have onFollow event to cancel onRowClick) 

Thanks

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by nichita-pasecinic** [comment]
```js
event.stopPropagation()
```
works as expected

**Comment by pan-kot** [comment]
Hello,

Please notice that our onRowClick API on the table is not recommended to use as a combination of clickable rows and clickable row elements results in a non-optimal user experience. Even if you can resolve the click handlers, the users might struggle to click the right thing.

I would recommend you to re-evaluate the need for onRowClick and try other options such as making table rows selectable and offering an action on the selected row(s) in the header.

Table API: https://cloudscape.design/components/table/?tabId=api

**Comment by nichita-pasecinic** [comment]
Thanks @pan-kot, 

From user perspective, isn't easier to just click on table row (an row item itself) and trigger the selection (to open the split panel) than finding the radio button (first column) to click on ?

I believe that is the approach used on several aws console tables.

Thanks!

**Comment by pan-kot** [comment]
It could be that for some experiences clicking on the row is easier. However, if, say, there are more clickable targets like links, or maybe you decide to make cell data editable inline - the clickable rows are no longer that great.

As a design system we try to come up with patterns that are consistent and reusable. It is true that some consoles might not yet have a chance to adopt those so the recommended approach here is to follow our guidance and demos.

Surely there is more than one way to make the users happy so if something works for you - that's great. We are happy to learn from your stories and improve!
