### ISSUE TITLE
[Bug]: `Table` scroll on `SplitPanel` open

### ISSUE THREAD

**Issue by nichita-pasecinic** [cloudscape-design/components#459]
### Package version

^3.0.95

### React version

^17.0.2

### Description

Table header scrolls to top when split panel is open and there are a few `items` in table (e.g.: 2...5)

### Reproduction

Could be easily reproducible in your [demos](https://github.com/cloudscape-design/demos) applications repository in `Split panel multiple` example (`http://localhost:9615/split-panel-multiple.html`) 

- Just set the number of `items` to be low (like 2...5) [here](https://github.com/cloudscape-design/demos/blob/575288af62882b923d1c825b9809f9251ec8c1dd/src/resources/ec2-instances.js#L5) 

- Open the Split panel 

- scroll down 

![image](https://user-images.githubusercontent.com/98735377/200860153-8e981f9e-6100-4b08-a4d3-7e004d9d97bb.png)

![image](https://user-images.githubusercontent.com/98735377/200860256-b86f9dfa-2c28-4a31-8f03-ad98dd0cc79d.png)

The table header should stick to the last visible row and not to allow more to scroll.
It should similar to this one
![image](https://user-images.githubusercontent.com/98735377/200860698-36f932f6-57b9-4523-aedd-abbee00c6a3a.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by nichita-pasecinic** [comment]
Hi @pan-kot, any updates (ETAs) on this issue ?

**Comment by connorlanigan** [comment]
We're currently working on fixing this bug. There is no ETA that we can provide. We will update this ticket when a fix is available.

**Comment by just-boris** [comment]
Released in [3.0.127](https://github.com/cloudscape-design/components/releases/tag/3.0.127)
