### ISSUE TITLE
[Feature Request]: `onFollow` should be triggered on mouse wheel click 

### ISSUE THREAD

**Issue by nichita-pasecinic** [cloudscape-design/components#464]
### Description

Hello,

In my understanding the  `<Link/>`  is a wrapper around `a` tag and should mimic its behaviour and usage, with some enhacements.

So, shouldn't then the `onFollow` prop from the `<Link/>` receive information about the click event itself, whether it is an `auxclick` click event or simple `onclick`.

This will allow to add functionality to the `Link` with a custom `onFollow` (that is mostly used) such as open in new tab with wheel click

Thanks!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by nichita-pasecinic** [comment]
Actually adding a right `href` in combination with the `onFollow` and `event.preventDefault()` solved it. 😅

**Comment by pan-kot** [comment]
Hello,

Please notice that our `onRowClick` API on the table is not recommended to use as a combination of clickable rows and clickable row elements results in a non-optimal user experience. Even if you can resolve the click handlers, the users might struggle to click the right thing.

I would recommend you to re-evaluate the need for `onRowClick` and try other options such as making table rows selectable and offering an action on the selected row(s) in the header.

Table API: https://cloudscape.design/components/table/?tabId=api
