### ISSUE TITLE
[Bug]: Tab with a 'href' will still navigate even if 'disabled' is true

### ISSUE THREAD

**Issue by rikkuness** [cloudscape-design/components#478]
### Browser

Chrome

### Package version

v3.0.111

### React version

v18.2.0

### Description

When using the `<Tabs>` component, if I have a tab that is set to disabled, but also has a href, then clicking on the tab will still navigate to the href. 

### Reproduction

https://codesandbox.io/s/sleepy-fog-j3d22t

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by taheramr** [comment]
Hello Darrian, 

Looking at your description the `Tabs` component does not have a `href` property and the codesandbox does not show any tabs, can you provide us with another example?

**Comment by rikkuness** [comment]
Thanks for the quick fix!

**Comment by rikkuness** [comment]
Looks like the PR merged now so I'll close this, thanks again

**Comment by connorlanigan** [comment]
I'm re-opening this ticket because the fix has not yet been released on NPM.

**Comment by just-boris** [comment]
Fixed in [v3.0.127](https://github.com/cloudscape-design/components/releases/tag/3.0.127)
