### ISSUE TITLE
[Bug]: TagEditor is stucking with "Loading key values" when using React.StrictMode

### ISSUE THREAD

**Issue by fr0stf0x** [cloudscape-design/components#483]
### Browser

Chrome

### Package version

3.0.116

### React version

18.2.0

#### Actual behavior:
`<TagEditor />` is stucking with "Loading key values" text when using `<React.StrictMode />`

Turn off <StrictMode /> then it will be fine

#### Expected behavior:
`<TagEditor />` should load keys successfully when using `<React.StrictMode />`

### Source code

https://codesandbox.io/s/confident-frog-zxflx8

### Reproduction

https://codesandbox.io/s/confident-frog-zxflx8

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by taheramr** [comment]
Hello, 
Thanks for reaching out! We are working on resolving this issue and will provide updates on this issue.

**Comment by fr0stf0x** [comment]
It seems like the bug is fixed in 3.0.127, isn't it @taheramr?

**Comment by just-boris** [comment]
Yes, it is. Resolving
