### ISSUE TITLE
[Bug]: Header component's `description` field may have invalid children

### ISSUE THREAD

**Issue by rikkuness** [cloudscape-design/components#496]
### Browser

Chrome

### Package version

v3.0.118

### React version

v18.2.0

### Description

The `description` property of the `<Header>` component accepts a `ReactNode` for content but the component renders the `ReactNode` inside of a `<p>` tag [as seen here](https://github.com/cloudscape-design/components/blob/3.0.118/src/header/internal.tsx#L69-L79), this means that setting `description` to anything but a [valid phrasing content](https://html.spec.whatwg.org/#the-p-element) will result in a warning such as:
```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```

### Reproduction

https://codesandbox.io/s/frosty-cache-4jum1t?file=/src/App.js

In the above CodeSandbox the warning can be seen in the console.

The `CopyText` component I used as a child component in the `description` is from the demo repo https://github.com/cloudscape-design/demos/blob/main/src/pages/commons/copy-text.jsx 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by taheramr** [comment]
Hello, 

the `description` field is meant to have supplementary text below the heading as mentioned in our [docs](https://cloudscape.design/components/header/?tabId=api). 

The idea behind having this property accept `ReactNode` type of content is to allow you to add links or add text styles ( bold, italic ) to your description text. A paragraph is used for accessibility reasons and to make the header component semantic.

**Comment by rikkuness** [comment]
That's cool, if this is an expected behaviour we can close this issue, it's only a warning anyway, I can deal with warnings 😄
