### ISSUE TITLE
[Bug]: Not specifying a label on an AttributeEditor definition throws off alignment

### ISSUE THREAD

**Issue by rikkuness** [cloudscape-design/components#498]
### Package version

v3.0.118

### React version

v18.2.0

### Description

`AttributeEditorProps.FieldDefinition` permits for an undefined label, but if you do not define a label then the alignment of the  fields is thrown off. As show below

![image](https://user-images.githubusercontent.com/3525311/202715168-5ad5c732-49cd-43d7-891d-e0cae77b09b9.png)

### Source code

```
<AttributeEditor
  addButtonText="Add new item"
  definition={[
    {
      label: "Key",
      control: (item, index) => (
        <Input value={item.key} placeholder="Enter key" />
      )
    },
    {
      control: (item, index) => (
        <Input value={item.value} placeholder="Enter value" />
      )
    }
  ]}
  removeButtonText="Remove"
  empty="No items associated with the resource."
/>
```

### Reproduction

https://codesandbox.io/s/gallant-voice-m8r48d

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by connorlanigan** [comment]
Hello,

we recommend to always provide a label for the field. The label is necessary to ensure the usability and accessibility of the interface.  
Is there a specific use case that requires you to omit the label?

**Comment by rikkuness** [comment]
I was using the component with a single field definition inside of a FormField, the labelling I did on the FormField itself and omitted it on the AttributeEditor, which is when I noticed the Add/Remove buttons were misaligned.

If a label should always be specified that's okay too, but in that circumstance I'd expect the `AttributeEditorProps.FieldDefinition` interface to be aligned to that and not allow an undefined string.

**Comment by connorlanigan** [comment]
I see. In that case I'd recommend to not wrap the Attribute Editor in a FormField, since most of the functionality is also exposed on the Attribute Editor directly as part of the `definition` (e.g. constraint text, error state/text, info links).

The Typescript interface indeed currently does not enforce the requirement for a label to be present, but this cannot be changed in a backwards-compatible way, so it will not be updated in the current major version.

**Comment by rikkuness** [comment]
That's cool, that works for my use case, I guess for the future either change that interface in a major release to make label required or update the styling so if it is undefined at least don't collapse the component?

**Comment by just-boris** [comment]
Yes, we are likely to change type definitions when we will be able to.

Closing the request, because currently we have no major version release planned
