### ISSUE TITLE
[Bug]: `AppLayout` with contentType 'table' on `SplitPanel` does not have full width `header`

### ISSUE THREAD

**Issue by fr0stf0x** [cloudscape-design/components#505]
### Browser

Chrome

### Package version

3.0.116

### React version

18.2.0

### Description

`AppLayout` with contentType 'table' on `SplitPanel` being scroll down does not have full width `header` when selecting more than 2 items

#### Note: this is not similar to already reported bug https://github.com/cloudscape-design/components/issues/459

Actual behavior:

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/6152718/202963620-e4f7130e-9ba7-48e7-8a73-b6a805743aa1.png">

Expected behavior: AppLayout header should have full width

### Reproduction

Could be easily reproducible in your [demos](https://github.com/cloudscape-design/demos) applications repository in Split panel comparison example (https://cloudscape.design/examples/react/split-panel-comparison.html)

Steps: 

1. Select 2 items

2. Scroll down

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by fr0stf0x** [comment]
Here is some devtool screenshots:

Working:

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/6152718/202964467-edb93ff5-1b6d-408e-b504-c8213cb702d2.png">

Bug:

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/6152718/202964670-c2058ae7-1c5f-48b0-9030-2bd0c416ed73.png">

**Comment by connorlanigan** [comment]
Hello,

we are currently working on a fix for this bug. We will provide an update this ticket when a fix has been released.

**Comment by just-boris** [comment]
Released in [3.0.127](https://github.com/cloudscape-design/components/releases/tag/3.0.127)
