### ISSUE TITLE
[Bug]: `TagEditor` does not trigger `keysRequest`

### ISSUE THREAD

**Issue by nichita-pasecinic** [cloudscape-design/components#506]
### Package version

^3.0.95

### React version

^17.0.2

### Description

Hi,

`keysRequest` should be triggered on every click on `Key` autocomplete field.
In my case the keys for tags are depended on another (select) field, If I change it then available tags (for autocomplete) should be re-fetched. But currently the `keysRequest` is getting triggered only on first input focus and after a input is received from user.

1. A user could first focus on tag key field (triggering a `keysRequest` with empty `[]`)
2. Then user could change the value of a `Select` field (that should possibly have some tags values)
3. Then user could again focus on tag key field (this time the tags should be fetched accordingly to value from `Select` field, but `keysRequest` is not getting invoked)

Thanks!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by connorlanigan** [comment]
Hi,

the TagEditor intentionally does not fire the `keysRequest` event every time the input is focused, since this would cause an unnecessary overhead of requesting the same keys again and again. If the keys depend on an outside state like in your case, I would recommend to render a new instance of the TagEditor by using React's `key` property. This way the internal state of the component will be reset.

For example:
```
const [selectValue, setSelectValue] = useState(...);

...

return <TagEditor
               key={selectValue}
               ... 
            />
```

**Comment by nichita-pasecinic** [comment]
Hi @connorlanigan ,

Thanks for the explanation and workaround, you are right this will do, different key will force react to re-render the component. 
But `TagEditor` component itself has a fade in effect for the text and it is quite noticeable when it re-render often (due to `key` linked to an input state).

Here is an example - https://codesandbox.io/s/sparkling-waterfall-djssgj?file=/src/App.js

**Comment by gethinwebster** [comment]
> Thanks for the explanation and workaround, you are right this will do, different key will force react to re-render the component. But `TagEditor` component itself has a fade in effect for the text and it is quite noticeable when it re-render often (due to `key` linked to an input state).

This was a bug, and has now been fixed in a recent release of @cloudscape-design/components. Hopefully this helps to resolve the issue @nichita-pasecinic?

**Comment by nichita-pasecinic** [comment]
@gethinwebster yes, thank you, issue solved 😄
