### ISSUE TITLE
[Feature Request]: `TagEditor` required fields

### ISSUE THREAD

**Issue by nichita-pasecinic** [cloudscape-design/components#508]
### Description

Hi, 

Would be nice to have required validation for tag key value fields (currently only tag keys are required).

![image](https://user-images.githubusercontent.com/98735377/203064114-c6b34586-8fcb-4374-8e54-50bc4ea6076c.png)

In my use case some specific keys should always be required (not optional)

Thanks!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by johannes-weber** [comment]
Hi @nichita-pasecinic, for this custom use-cases you can use [Attribute editor component](https://cloudscape.design/components/attribute-editor/?tabId=playground&example=default).
This is another more low-level component in which you can specify your own rules.

**Comment by nichita-pasecinic** [comment]
@johannes-weber Thanks, already figured it out 😄
