### ISSUE TITLE
[Feature Request]: Expose onDismiss event on popover

### ISSUE THREAD

**Issue by solamanhuq** [cloudscape-design/components#518]
### Description

Can the `Popover` component expose an `onDismiss` Event?

In my case, I have an a copy icon that, once clicked, copies some content, changes to a checkmark and opens a Popover. Once the Popover is closed I'd like to revert the checkmark back to a copy icon.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by timogasda** [comment]
Hi @solamanhuq !

Is there a reason why you're not using the existing Copy to Clipboard pattern? See https://cloudscape.design/components/copy-to-clipboard/.

**Comment by solamanhuq** [comment]
hey @timogasda ! thanks for following up!

Plainly, I like how Github handles Copy to Clipboard. Call it preference but it feels more responsive.
- changing the icon to a green checkmark is highly visible to  _abled_ end users...no reading involved.
- Naturally we want to change the icon back.

Perhaps a counter argument is a lack of accessibility, but isn't that the purpose of the popover anyway? An additional visual indicating the same thing doesn't limit access to impaired users.

**Comment by gethinwebster** [comment]
Thanks for providing the extra feedback here. We don't currently plan to change the copy to clipboard pattern as we believe that having a single feedback/success mechanism (the popover) is optimal, and as such don't see a strong need for this additional event.
