### ISSUE TITLE
[Bug]: Label duplication for empty filtering options in PropertyFilter

### ISSUE THREAD

**Issue by iancaffey** [cloudscape-design/components#523]
### Browser

Chrome, Safari, Firefox, Edge

### Package version

LATEST

### Description

When using **PropertyFilter**, if you pass in a filteringOption with an empty string as the value, the label displayed to users for the corresponding Option looks like  `Instance ID = Instance ID =` (e.g. `{propertyLabel} {op} {propertyLabel} {op}`).

Tried taking a peek at what's going on behind the scenes (hope this helps to expedite identifying/replicating the issue),

It appears that in the PropertyFilter controller,
- prefix is `property.propertyLabel + ' ' + (operator || '=')` 
- value is `property.propertyLabel + ' ' + (operator || '=') + ' ' + filteringOption.value`
- label is the filtering option value (which is empty string in this case)

And since Option passes `option.label || option.value` when creating the Label, looks like that's where the duplicate could be introduced.

I'm not sure when this behavior change was introduced, to be honest. I think I remember PropertyFilter used to drop empty filtering options in the past?

I'm mitigating it on my side by dropping all filtering options which had an empty value, but this was definitely not necessary in the past.

### Reproduction

Can easily reproduce it in the playground (https://cloudscape.design/components/property-filter) by changing any of the filteringOptions to `''` and start building a token. 

When it shows the dropdown of values to complete the token, it'll show the duplicate label.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by connorlanigan** [comment]
Hi,

thank you for reporting this. We've reproduced the issue. We will provide an update in this ticket when a fix is released.

**Comment by timogasda** [comment]
Hello @iancaffey !

Apologies for the late response. This issue should have been resolved with the mentioned PR (https://github.com/cloudscape-design/components/pull/530). Please update your Cloudscape version and try again.
