### ISSUE TITLE
Add dark mode palette to Figma design system?

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#675]
### Describe the feature

Currently, there is no dark mode color palette within the Figma design system. Is it possible to have a dark mode version as well?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by aszuchie** [comment]
Hey, thanks for reaching out. Every console needs to be delivered in Light and Dark modes. We recommend designing in Light mode; then when the product is implemented in Cloudscape, it is trivial to switch to dark mode. Maintaining a Dark mode Figma library at this time is high effort, low return, as we cannot use Plug-ins to switch between color themes. We do understand your needs to work with dark mode and currently collecting more data to understand those needs better. Please leave a comment describing your use case in more details. This is be super helpful to prioritise our work.

**Comment by shanayau** [comment]
> Hey, thanks for reaching out. We recommend designing in Light mode; then when the product is implemented in Cloudscape, it is trivial to switch to dark mode. Maintaining a Dark mode Figma library at this time is high effort, low return, as we cannot use Plug-ins to switch between color themes. We do understand your needs to work with dark mode and currently collecting more data to understand those needs better. Please leave a comment describing your use case in more details. This is be super helpful to prioritise our work.

I see how at this moment maintaining a Dark mode library in Figma is high effort, low return. I apologize if I didn't explain myself properly. What I mean by adding a dark mode color palette is to add the dark mode color styles to the Figma library, or rather noting which color styles are meant for dark mode and which are meant for light mode. I've noticed that on the cloudscape.design website, it's difficult to tell which colors are meant for dark mode. Would it be possible to get a Dark mode version of the Color Palette attached? Thank you and please let me know.
![Color Palette](https://user-images.githubusercontent.com/123783898/215552093-20618ba9-536b-46e0-8aee-9ffa66d95665.png)

**Comment by aszuchie** [comment]
Thank you for your feedback and providing more context. You can find the system color palets for dark mode on this page: https://cloudscape.design/foundation/visual-foundation/colors/. You can also find guidance on the data visualisation color pallet here: https://cloudscape.design/foundation/visual-foundation/data-vis-colors/. Please let me know if this is what you were looking for. Thanks!

**Comment by portia-o** [comment]
We have included our design tokens in the description field for many of the color styles in the Figma library. You can see it here. We are planning to add further dark mode support to our library in the future. Thank you for this suggestion!

<img width="584" alt="image" src="https://user-images.githubusercontent.com/7318599/229623292-800ce5d2-043b-4081-be57-dab054196baf.png">
