### ISSUE TITLE
Create navigation sidebar that includes logos component

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#680]
### Describe the feature

In the current Figma design system, the navigation sidebar component does not allow icons to be added to the left single menu items. Is it possible to add that ability to the existing system in Figma?
<img width="382" alt="Screen Shot 2023-01-30 at 2 43 26 PM" src="https://user-images.githubusercontent.com/123783898/215613043-ab1b62b1-d0f2-4b0b-a9c1-4d27e78ca0c0.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by aszuchie** [comment]
Hello,

Thanks for reaching out to us. I added this ticket to our board for further investigation.

Thanks,
Anna
