### ISSUE TITLE
Create card component that supports logos/icons/images

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#681]
### Describe the feature

Currently, the card components in Figma do not allow you to add logos/icons/images to them without detaching the component from the design system. Is it possible to add this ability? Thanks!
<img width="237" alt="Screen Shot 2023-01-30 at 3 01 08 PM" src="https://user-images.githubusercontent.com/123783898/215616008-faa19852-b363-4d60-95dc-5b9468a8ee99.png">
<img width="282" alt="Screen Shot 2023-01-30 at 3 02 44 PM" src="https://user-images.githubusercontent.com/123783898/215616258-2baa44cb-1e2c-4d5d-93bb-5159d2389f21.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by aszuchie** [comment]
Hello,

Thanks for reaching out to us. I added this ticket to our board for further investigation.

Thanks,
Anna

**Comment by portia-o** [comment]
This is a great request; we will be updating the library later this year and we plan to include it then.

**Comment by portia-o** [comment]
We are releasing a new Figma library in Q2 which is a big upgrade from the existing one. We plan to add a placeholder component to the cards so that you can put anything you want in there. I'll close this for now, but feel free to reach back out if the new library doesn't meet your needs.
