### ISSUE TITLE
Can more Cloudscape tutorials and resources for designers, similar to what they’ve created for the developers, be created?

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#682]
### Description

Currently, there is only one workshop on Cloudscape, targeted for front end developers:  https://workshops.aws/?tag=Cloudscape 

Will more workshops be added as resources for UX designers? Possibly with tutorials on how to create a product/app using the Cloudscape design system in Figma?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by aszuchie** [comment]
Hello,

Thanks for reaching out to us. You can check our https://cloudscape.design/ for design guidelines, demos and resources. Could you share what kind of tutorials would you be interested in?

Thanks,
Anna

**Comment by portia-o** [comment]
This is a great suggestion; we will consider adding demos / tutorials in a future version of our Figma resources.

Thanks,
Portia

**Comment by at-susie** [comment]
Hi @shanayau,

Thank you for the suggestion. Although the ETA is not specified, we have a plan to release demos in Figma, which you can find in [the demos page](https://cloudscape.design/demos) in the Cloudscape website, that will help you see how pages can be built using the Cloudscape components.

Best Regards,
Atsushi
