### ISSUE TITLE
[Feature Request]: Tokens to manipulate rounded corners

### ISSUE THREAD

**Issue by bolora** [cloudscape-design/components#69]
### Description

The visual refresh theme is great but there will be consumers of Cloudspace that require a design system without rounded corners or may need to adjust the size or rounded corners. 

Consumers should be able to:

- Globally control rounded corners in the entire system with a single boolean value. It should be set to true by default. Setting the token to false will automatically set all tokens that affect border-radius to 0. Twitter Bootstrap has this feature and it is simple enacted by overriding this scss variable: https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L338
- There should be tokens to adjust rounded corner values. Something like base, small, medium, large, etc. For example, a consumer may want to reduce the roundness of the primary button. Right now the only way to do this is to create a custom class to hack the original qualities of buttons or any other rounded UI element.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by FlorianDr** [comment]
Hey Bo, 

thank you for reaching out. A theme-able design token for border radius on various component groups seems like a reasonable addition to the theming capabilities. However, we currently don't have any plans for making this change. 

I will keep this issue open to collect any additional feedback. Feel free to share more information about your use case for theme-able border radius and how you would use it in your application. 

Thank you,
Florian

**Comment by lasley** [comment]
Thanks for the explanation @FlorianDr. Would you accept the change in the form of a PR?

**Comment by FlorianDr** [comment]
That's correct! For now, we don't accept PRs for enhancements, until we have found a good contribution model both for contributors and maintainers. Do you already have a fork/PR ready?

**Comment by lasley** [comment]
@FlorianDr - not at this time; I'd like to avoid effort if it won't be accepted. We're in the process of identifying whether CloudScape will work for our use case, and rounded corners was one of the reasons it wouldn't. This issue was a test of waters to understand how/if our needs could be integrated into this design system.

**Comment by fralongo** [comment]
@bolora @lasley we have just released public and themeable design tokens for border radius. In our documentation website you can find:
- The [list of border radius tokens](https://cloudscape.design/foundation/visual-foundation/design-tokens/#tokens).
- Additional [implementation guidelines for theming](https://cloudscape.design/foundation/visual-foundation/theming/#implementation).
