### ISSUE TITLE
Add dark mode state for Segmented Control component

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#692]
### Describe the feature

Currently, there is no dark mode state for the Segmented Control component in the Figma design system. See attached. Is it possible to get this added? Thanks!
<img width="226" alt="Screen Shot 2023-02-01 at 12 30 51 PM" src="https://user-images.githubusercontent.com/123783898/216156616-98a01555-5145-4c6e-9b44-d061000d6f3b.png">
<img width="230" alt="Screen Shot 2023-02-01 at 12 31 40 PM" src="https://user-images.githubusercontent.com/123783898/216156758-b31036a8-6396-4b90-a1d0-79610547450b.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by aszuchie** [comment]
Hey, thanks for reaching out. We recommend designing in Light mode; then when the product is implemented in Cloudscape, it is trivial to switch to dark mode. Maintaining a Dark mode Figma library at this time is high effort, low return, as we cannot use Plug-ins to switch between color themes. We do understand your needs to work with dark mode and currently collecting more data to understand those needs better. Please leave a comment describing your use case in more details. This is be super helpful to prioritise our work.

**Comment by shanayau** [comment]
> 

Hello. I understand maintaining a Dark mode Figma library is high effort, low return. I am confused because there are some components where dark mode is provided (like buttons) but some where that style is not there (like in segmented components). It gave the impression that the Figma library is unfinished, so I am curious to know why some components have a dark mode toggle, but some do not.

**Comment by shanayau** [comment]
Additionally, we have clients that are requesting products in dark mode, but will not sign off on the designs if they are not in dark mode. While it is possible for us to recreate dark mode by changing the colors manually, this opens the door for inconsistencies between designers and between designers and developers.

**Comment by aszuchie** [comment]
Thank you for providing more context. Those are all valid points. Your feedback has been noted and we will make sure to look into the topic. Some components of the light mode, eg. table, have dark versions of elements (select, actions stripe, buttons) because they are displayed on the dark background of the header.

**Comment by portia-o** [comment]
We will include this in our next version of the Cloudscape Design System component library in Figma, as Segmented control is a component that might appear in the dark header. 

Best,
Portia
