### ISSUE TITLE
Add top navigation state to App Layout component

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#693]
### Describe the bug

Cloudscape offers a ‘top navigation' component, but, unlike the side navigation or help panel, there is no state on the App Layout to turn “top navigation” on or off. To use the top nav, you have to drop the component right above the App Layout and then join them together via auto layout, but I don’t think that’s the flow that was intended. Will this be updated in the Figma design system, or was this the original intended flow?
![image](https://user-images.githubusercontent.com/123783898/216159366-69122175-3d5a-4546-bcf4-42a32fdf6afa.png)
![image](https://user-images.githubusercontent.com/123783898/216159412-e288d665-df10-46f1-b19f-cdc1349a0414.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by aszuchie** [comment]
Hello, thanks for reaching out. We're looking into the topic.

**Comment by portia-o** [comment]
This has been resolved with the latest [Figma component library update](https://www.figma.com/community/file/1217512017324273815).
