### ISSUE TITLE
Possible to create footer component designed for Desktop in Figma?

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#696]
### Describe the feature

Currently, there is no footer component for desktop screens. I noticed there is an example of one in the cloudscape.design website. Is it possible to add that to the current system in Figma?
<img width="1920" alt="Screen Shot 2023-02-01 at 3 27 40 PM" src="https://user-images.githubusercontent.com/123783898/216190712-379f2536-2e78-43f4-9379-fe6d4df99fdf.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by aszuchie** [comment]
Hello, thanks for reaching out. Currently we don't have a footer component available in our Design system.

**Comment by portia-o** [comment]
Hello!

Thanks for this request. We don’t have a plan for adding a footer in the short-term future. As Anna mentioned above,you can create your own footer if you'd like; we think this would have to be a custom component for each organization. 

Best, 
Portia
