### ISSUE TITLE
[Feature Request]: Implementation for FileUpload component

### ISSUE THREAD

**Issue by jasmaa** [cloudscape-design/components#70]
### Description

Docs describe a [file upload component](https://cloudscape.design/components/fileupload/) but it appears this component is not directly available in the library. File upload is non-trivial to implement and the documented example for multiple file upload does not appear to be replicable externally since `TokenGroup` does not allow for components within Tokens.

Since file uploaders are a common need and consumers currently require additional effort to implement them, I think it would be great if we could have a FileUpload implementation directly available in the library that follows the specification described in the docs.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by FlorianDr** [comment]
Hey Jason,

thank you for reaching out. That's correct! The systems describes the user experience on the [website](https://cloudscape.design/components/fileupload/), but it does not provide an implementation as part of the library. We are aware of this feature request, but we don't currently have short-term plans to work on it. For now, you can get around by creating your own adjacent component using a button and a custom file list implementation.

We will use this issue to track interest in having a FileUpload implementation. 

Thank you, 
Florian

**Comment by jeffshep** [comment]
Given the commonality of this feature, its absence could be a blocker for adoption for us. Love the ease-of-use of the existing components though!

**Comment by XTEKiyZRLr8UsiQN** [comment]
Agreed, was really excited to see how clean the file upload example was only to find out it wasn't actually part of the components. In the short term, if the image in the example was generated and not just a mock, would it be possible to paste the source code here?

**Comment by jjdirvin** [comment]
@FlorianDr Any updates on this request?  My team was really excited to use this.

**Comment by just-boris** [comment]
Hello!

There are no particular plans for this request. It stays here for visibility, but not prioritised in any way

P.S. Best is not to ping individual people, because they may change their projects. Just leave a comment and our team will be notified regardless.

**Comment by jasmaa** [comment]
FWIW, I've been working on a file uploader implementation if anyone is interested: https://github.com/jasmaa/cloudscape-file-uploader

**Comment by pan-kot** [comment]
Hello!

Cloudscape team is working on implementing the file upload component, please bear with us!
