### ISSUE TITLE
Text Area component does not have a state where a permanent label can be above the field

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#747]
### Describe the bug

The text area component does not have a state where a label can be added. I believe a label state may be missing, see forms component screenshot.
<img width="500" alt="Screen Shot 2023-02-10 at 10 19 24 AM" src="https://user-images.githubusercontent.com/123783898/218167089-8a5c47ff-6f6d-41f2-98ee-229f619bce4f.png">

<img width="580" alt="Screen Shot 2023-02-10 at 10 19 37 AM" src="https://user-images.githubusercontent.com/123783898/218167120-8e0e1414-ea3d-4580-a595-ebceb44dbc3a.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by linluiux** [comment]
Hey, thanks a lot for reaching out. Form field has a text area type and customers can toggle on optional/info label property in the property panel (Figma). Please try to change the form field type to text area, instead of using text field component in Figma. 
Let us know if this will get you need or not.

**Comment by shanayau** [comment]
> Hey, thanks a lot for reaching out. Form field has a text area type and you can toggle on optional/info label property in the property panel (Figma). Please try to change the form field type to text area, instead of using text field component in Figma. Let us know if this will get you need or not.

Hi, I tried to do so but I don't see the text area option. Is this where I was supposed to look?
<img width="230" alt="Screen Shot 2023-02-15 at 11 12 28 AM" src="https://user-images.githubusercontent.com/123783898/219129132-146f1039-0e8f-400d-9b8a-6bfe5246d772.png">

**Comment by linluiux** [comment]
Hi, yes it should be. Sorry for the mismatched information. The text area option in form field has not been updated in open source version in Figma yet. We are working on updating the library for Figma community. Thanks a lot for the feedback! I will let you know once it's there.
Currently, please try to swap the "input" instance inside form field with "text field" to get a text area type of form field. Sorry again for the inconvenience.
