### ISSUE TITLE
[Bug][Design]: Dropdown behaviour isn't consistent in Autosuggest

### ISSUE THREAD

**Issue by dkhos17** [cloudscape-design/components#751]
### Package version

v3.0

### React version

v17.0.2

### Description

In `Autosuggest` when there isn't enough space down, the list displays up:
1). while list displays upside, if we (play a bit with input) or use remove/clear `button` in `Autosuggest`, it'll display below with the exact same list - so with one given state dropdown direction / behaviour isn't consistent. (I think the same listener functionality isn't handled for `button` click, as it is on `input` click.)
2). while dropdown is displayed up, user still need to use `down` keyboard to navigate while it is logical to use `up` on that case.

As for Package and React version, I'm not sure about them but what I've found is `"react" : >= 17.0.2` and using Polaris 3 which I guess is >= v3.0, let me know if there are more details needed, or screens.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by gethinwebster** [comment]
The keyboard behavior of this component is a deliberate implementation decision: amongst other things, it's necessary to provide a consistently accessible experience to e.g. users using assistive technology, who may not have the visual cue of whether the dropdown is appearing above or below the input, so would always expect to navigate 'down' into the list of items. It is also consistent with the native operating system behavior of similar input/autocomplete components.

Regarding the positioning, we don't consider this as a bug as such, but will make a note of this in case we see further feedback that suggests this causes confusion or usability problems.

**Comment by dkhos17** [comment]
Thanks for quick feedback! I see the point on accessibility part and agree, but as for UX I think inconsistent dropdown direction still might need to be overlooked again once you have chance. Anyway, thanks again!
