### ISSUE TITLE
No way to select number of slices in Pie Chart

### ISSUE THREAD

**Issue by shanayau** [cloudscape-design/components#767]
### Describe the bug

There is currently no way to edit the number of slices in the pie chart component. The only way to do so requires breaking the component. 
<img width="230" alt="Screen Shot 2023-02-15 at 4 00 54 PM" src="https://user-images.githubusercontent.com/123783898/219222912-1248d776-ded7-4c58-b531-871586b7caaf.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by linluiux** [comment]
Hey, thanks a lot for reaching out. We have this as a known issue in the backlog. The next version of the OS library has pieces for small donut one and it will be published soon. Sharing more thinking behind this ask, adding configurability to charts will increase the file sizes and potential outage in Figma. I wonder how many /types of slices are you expecting to include inside charts?

**Comment by shanayau** [comment]
> Hey, thanks a lot for reaching out. We have this as a known issue in the backlog. The next version of the OS library has pieces for small donut one and it will be published soon. Sharing more thinking behind this ask, adding configurability to charts will increase the file sizes and potential outage in Figma. I wonder how many /types of slices are you expecting to include inside charts?

I think we're expecting to use 5-7 typically, but for those unusual cases I think a max of 12 to use would be helpful! Thank you so much!

**Comment by linluiux** [comment]
Thanks, I will note your advise down in the ticket in our backlog.
