### ISSUE TITLE
[Bug]: `Select` does not work in Next.js v13

### ISSUE THREAD

**Issue by MasahiroKanatani** [cloudscape-design/components#785]
### Browser

Chrome

### Package version

v3.0.206

### React version

v18.2.0

### Description

Hello. I am using Cloudscape with Next.js v13.
When I build and launch it with the Select component invoked and click on the Select box, I get the following error in the Developer Tool console.
(The error does not occur if I start the program in development mode).

```
TypeError: Cannot read properties of undefined (reading '__labelPrefix')
```

### Source code

Sample project is here.
https://github.com/MasahiroKanatani/next13-cloudscape-minimum

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by MasahiroKanatani** [comment]
Setting `swcMinify: false` in next.config.js worked as expected.

**Comment by Rathxxx** [comment]
I ran into the same issue yesterday working with the PropertyFilter component. The issue appears in functionality for select related to aria strings.

When built in nextjs for production this function appears broken as the undefined is related to a variable that is never set. 
![image](https://user-images.githubusercontent.com/20726702/221388318-fa37f759-eef3-4143-99b0-7d400d6feba3.png)

However everything is as you would expect unminified/optimized when running in development

**Comment by Al-Dani** [comment]
Hey @MasahiroKanatani ,
Thank you for reaching out! 
We will take a look into this error.

**Comment by just-boris** [comment]
This looks like a bug in SWC compiler: https://github.com/swc-project/swc/issues/7004

Until the issue is fixed stick to `swcMinify: false` option
