### ISSUE TITLE
[Documentation]: Adding hyperlink to README.md

### ISSUE THREAD

**Issue by KaevonD** [cloudscape-design/components#81]
### Description

Adding a hyperlink to Amazon Web Services (AWS) for quality of life.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by dhanvi1911** [comment]
Hi, I would like to solve this issue. Where do I get the README.md file?
