### ISSUE TITLE
[Bug]: Accessibility issue with status colors

### ISSUE THREAD

**Issue by murraylchapman** [cloudscape-design/components#838]
### Browser

Firefox

### Package version

3.0.228

### React version

Irrelevant

### Description

The colors chosen to represent status (red/green) are too similar for people with deuteranopia to distinguish, especially in light mode. While the colors used in this version of Cloudscape Design are better than the ones used in Polaris, they still represent a challenge for 8% of the male population to distinguish, requiring extra time and leading to potential mistakes. More dramatic contrast between the red and green colors would remove this problem. 

Accommodating this disability is a legal requirement under ADA; see here for more information: https://adasitecompliance.com/color-blind-website-accessibility/

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by connorlanigan** [comment]
Thank you for your feedback, we will refer this issue to our accessibility team for review. If you have additional questions or feedback regarding the accessibility of Cloudscape, please contact aws-accessibility@amazon.com.

**Comment by gethinwebster** [comment]
Thank you for your report. We reviewed your issue and determined that there is no action required at this time because the red and green colors are not used to provide meaning without another non-color indication.
