### ISSUE TITLE
[Feature Request]: Disable inline editing for specific cells in a table

### ISSUE THREAD

**Issue by cogwirrel** [cloudscape-design/components#854]
### Description

Inline editing in a table is really useful, but I can't see a way to disable it for particular cells.

An example might be displaying a list of resources that the logged in user may or may not have permissions to edit. It would be a nicer UX to disable editing values for resources that the user does not have permissions to edit, rather than having them make their edit and get an error message back from the server.

As a workaround I can do something a bit like this in my column definition:

```typescript
{
  id: "name",
  header: "Resource Name",
  cell: (cell) => cell.name,
  editConfig: {
    editingCell: (item, ctx) => {
      const value = ctx.currentValue ?? item.name;
      return isCurrentUserPermittedToEditResource(item) ? (
        <Input value={value} onChange={(e) => ctx.setValue(e.detail.value)} />
      ) : item.name;
    },
  },
},
```

But users can still click on an item and see the tick and cross.

Ideally I'd like to be able to specify something like:

```
editConfig: {
  disabled: (item): boolean => /* Return true/false based on whether the item can be edited */,
  ...
}
```

And when disabled returns `true`, the cell should not highlight on hover or display the editingCell when clicked.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
Also, reminder that our [contribution model](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#how-to-contribute-code) only allows for bug fixes. API additions require additional steps and we are not ready to accept them at the moment.

**Comment by timogasda** [comment]
Hello @cogwirrel !

I'm happy to announce that we have added a new `disabledReason` property on the table's `editConfig` property, which let's you disable inline editing for specific cells. All you have to do is provide a reason (in the form of a string).

PR: https://github.com/cloudscape-design/components/pull/1854

**Comment by cogwirrel** [comment]
Great news! Thank you! 😁
