### ISSUE TITLE
[Bug]: Cloudscape dropdown menu throws an error on option hover

### ISSUE THREAD

**Issue by JustinKim3420** [cloudscape-design/components#870]
### Browser

Safari

### Package version

v3.0.231

### Description

When using components that contain a dropdown select, the page will thrown an error. 
The page shows
`
Application error: a client-side exception has occurred (see the browser console for more information).
`
and the console shows
`
TypeError: undefined is not an object (evaluating 't.__labelPrefix')
`

### Source code

import * as React from "react";
import FormField from "@cloudscape-design/components/form-field";
import Select from "@cloudscape-design/components/select";
import Button from "@cloudscape-design/components/button";

```
const Home = () => {
  return (
    <FormField
      label="Security group"
      secondaryControl={<Button iconName="refresh" />}
    >
      <Select
        options={[
          { label: "option1", id: "1" },
          { label: "option2", id: "2" },
          { label: "option3", id: "3" },
          { label: "option4", id: "4" },
          { label: "option5", id: "5" }
        ]}
      />
    </FormField>
  );
}
```
export default Home

### Reproduction

First I ran the build command and started the application from the build using start
`
npm run build
`
`
npm run start
`

Once build, click on the select component to display the options, and once the option is hovered on, the page will throw an error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by abdhalees** [comment]
Hello Justin, 

an option must have a `value` property, `id` is not a valid property inside a `Select` option

**Comment by JustinKim3420** [comment]
Hey abdhalees,
Thanks for the quick reply! You are absolutely right on the incorrect object being used, however I just used a snippet from the docs 
https://cloudscape.design/components/select/?tabId=playground
```
import * as React from "react";
import Select from "@cloudscape-design/components/select";

export default () => {
  const [
    selectedOption,
    setSelectedOption
  ] = React.useState({ label: "Option 1", value: "1" });
  return (
    <Select
      selectedOption={selectedOption}
      onChange={({ detail }) =>
        setSelectedOption(detail.selectedOption)
      }
      options={[
        { label: "Option 1", value: "1" },
        { label: "Option 2", value: "2" },
        { label: "Option 3", value: "3" },
        { label: "Option 4", value: "4" },
        { label: "Option 5", value: "5" }
      ]}
      selectedAriaLabel="Selected"
    />
  );
}
```
And I still receive an error. Since the issue occurs only when building (using `npm build`) the app, I think the issue maybe with the NextJS change from Webpack to Turbopack.
