### ISSUE TITLE
[Feature Request]: Tutorial download should only be displayed if download link provided

### ISSUE THREAD

**Issue by pcolmer** [cloudscape-design/components#872]
### Description

We want to use the info panel, help text and tutorials to make our app/website self-documenting. As such, we don't want to provide a downloadable PDF of the tutorials.

However, the code, as it stands, will always try to display the download option. It should, instead, only display that if the download URL has been provided.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by abdhalees** [comment]
Hello Philip, 

thanks for the feedback, the download button is necessary to make the content more accessible for users who are using assistive technology and for accommodating for personal preferences.

**Comment by pcolmer** [comment]
> thanks for the feedback, the download button is necessary to make the content more accessible for users who are using assistive technology and for accommodating for personal preferences.

I appreciate those points but I don't think they should mean that the download button is *always* there. I can tell you that we will never be providing PDF versions of the tutorials - I don't have the skills to put that together.

Having the ability to hide the download button if there isn't a download, surely, is an appropriate thing to do and doesn't negate the desire to make content more accessible if an alternative *is* available?

**Comment by abdhalees** [comment]
We think that is a reasonable request, I'll work on a fix to remove the download link when `downloadUrl` is not available.
