### ISSUE TITLE
[Feature Request]: AppComposer canvas

### ISSUE THREAD

**Issue by atali** [cloudscape-design/components#944]
### Description

Do you plan to implement a canva component like the use in AppComposer ? or is there a way to do it with the composition of the current components already available in cloudscape ?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by just-boris** [comment]
Hello!

Our team builds generic components suitable for multiple use-cases. Individual service features do not belong to a design system.

If you meant a generic UI component in your request, please provide more details about your request

**Comment by just-boris** [comment]
Found a duplicate request from you: https://github.com/cloudscape-design/components/discussions/943

No, we have no plans building such component
