### ISSUE TITLE
Ability to turn off the the string that the user typed in on the autosuggest matching list

### ISSUE THREAD

**Issue by onlyone1004** [cloudscape-design/components#946]
### Description

**Current behavior:**
When user searches for a term in the autosuggest component, the suggested values contain the string that the user typed in as the first value of the searched term as the first one in the list. (screenshot attached)

<img width="517" alt="Source_SDK_Doc_for_JS" src="https://user-images.githubusercontent.com/130109166/231277622-110865ae-538c-41a1-9d3d-580dd3b70b29.png">
<img width="893" alt="Source_DX_HUB" src="https://user-images.githubusercontent.com/130109166/231277627-9d9bde10-b065-4419-b9f8-7d351bdd153e.png">

Is there a way for our developers to turn this feature off so that suggested list would only include the values that match the input string?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by mmarkelov** [comment]
I guess it will be easy to introduce, there is `hideEnteredTextOption`, I'm just not sure why it isn't configurable.

**Comment by just-boris** [comment]
Hello!

This behavior is a deliberate design decision. Users need to have an explicit way to decline suggestions and proceed with their current input.

In your case (search input, I guess) the  "Use: how" text should submit the search same way as clicking on any other suggestion would do.

Feel free to provide more comments and details about your use-case, but I will close the issue as currently not planned
