### ISSUE TITLE
[Bug]: Documentation/Project webpage seems to be broken

### ISSUE THREAD

**Issue by tomvonheill** [cloudscape-design/components#949]
### Browser

Chrome

### Package version

website

### Description

cloudscape.design is down. Also trying to look at the docs for any components doesn't work either. The error i'm getting is below. Not sure if this is the RIGHT place to report this, but didn't know where else to go to make people aware.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/10145413/231499024-5570cafb-e50e-4f2b-941e-9589d584dc67.png">

### Reproduction

Go to https://cloudscape.design/ from any browser

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by rubencarvalho** [comment]
Thank you for reaching out. Our team is aware and working on a fix. We hope to have it solved in the next few minutes.
