### ISSUE TITLE
[Bug]: jest test can't run - cannot use import statement ...

### ISSUE THREAD

**Issue by adnjoo** [cloudscape-design/components#96]
### Browser

Chrome

### Package version

3.0.10

### React version

v18.2.0

### Description

I'm trying to implement Cloudscape design in a simple React app. The UI runs fine; however when I run Jest tests I encounter a (import ...) bug. Here are my steps to reproduce the issue.

1. create react app using npx command
2. install cloudscape components using [the following guide](https://cloudscape.design/get-started/integration/using-cloudscape-components/)
3. run npm test
4. get the following error: `SyntaxError: Cannot use import statement outside a module`
![Screen Shot 2022-07-29 at 10 03 34 AM](https://user-images.githubusercontent.com/22807629/181809054-7d118462-001a-48c4-bf7d-e1b4342d625d.png)
 
I've tried to create babel.config.js and write certain settings, however to no avail. (as recommended by [SO](https://stackoverflow.com/questions/58613492/how-to-resolve-cannot-use-import-statement-outside-a-module-in-jest))

Any ideas on how to ameliorate this issue? 

### Source code

https://github.com/adnjoo/cloudscape-test/

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by 18clans** [comment]
I'm running into this issue too and tried using `ts-jest` with no luck.

https://jestjs.io/docs/getting-started#using-typescript

**Comment by adnjoo** [comment]
@18clans Hi I fixed this issue by replacing `test` with `react-scripts test --transformIgnorePatterns 'node_modules/(?!my-library-dir)/` inside package.json

**Comment by 18clans** [comment]
@adnjoo thank you for the fix.

**Comment by lasley** [comment]
For future peepz: CloudScape has a [`jest-preset`](https://github.com/cloudscape-design/jest-preset) package that takes care of this

**Comment by reillyjodonnell** [comment]
> jest-preset

Unfortunately if you're using CRA (like OP) this package is not usable unless you eject (which you should never do)

**Comment by reillyjodonnell** [comment]
> For future peepz: CloudScape has a [`jest-preset`](https://github.com/cloudscape-design/jest-preset) package that takes care of this

Unfortunately if you're using CRA (like OP) this package is not usable unless you eject (which you should never do)

**Comment by xuesichao** [comment]
>I fixed this issue by replacing react-scripts test with react-scripts test --transformIgnorePatterns 'node_modules/(?!my-library-dir)/ inside package.json.

Note: If you already set `transformIgnorePatterns` in your package.json, you will need to merge them.

For example:
```
// Before
"transformIgnorePatterns": [
  "<rootDir>/node_modules/(?!react-merge-refs)"
]

// After

"transformIgnorePatterns": [
  "<rootDir>/node_modules/(?!react-merge-refs|@cloudscape-design)/"
]
```
